// ─────────────────────────────────────────────────────────────────────────────
//  specs.js — data-driven creatures. Each is a compact parametric spec fed to
//  builder.js. Designed to be canon-accurate and visually distinct: archetype,
//  skin, palette and parts are chosen so every beast is recognisable on sight.
//  Tiers: common · uncommon · rare · ultra · legendary · mythic.
// ─────────────────────────────────────────────────────────────────────────────

const P = (o) => o; // tiny helper for readability

export const SPECS = [
  // ─────────────── COMMON ───────────────
  {
    id: 'flobberworm', name: 'Flobberworm', latin: 'Vermis flobberus', tier: 'common',
    blurb: 'A toothless brown worm that does little but eat lettuce. Utterly placid.',
    size: 0.5, speed: 0.7, roam: 4, diet: ['leafy_greens', 'berries'], favorite: 'leafy_greens',
    produces: { item: 'Flobber-mucus', amount: 6, every: 70 }, unlockCost: 30,
    care: { feed: 'Lettuce, endlessly', play: 'It mostly just lies there', note: 'The easiest beast to keep alive.' },
    build: { archetype: 'serpent', skin: 'smooth', palette: { base: 0x7a5a3a, belly: 0x9a7a52, accent: 0x5a4028, eye: 0x201810, spark: 0xbda47a },
      body: { len: 0.7, girth: 0.22 }, head: { shape: 'round', size: 0.5 }, eyes: { count: 2, size: 0.07 }, legs: { count: 0, type: 'none' }, tail: { type: 'serpent', len: 0.5 } },
  },
  {
    id: 'pygmypuff', name: 'Pygmy Puff', latin: 'Puffus pygmaeus', tier: 'common',
    blurb: 'A miniature Puffskein bred by the Weasley twins — a humming ball of pink or purple fluff.',
    size: 0.42, speed: 1.0, roam: 5, diet: ['sweet_truffle', 'honey_pot', 'berries'], favorite: 'sweet_truffle',
    unlockCost: 40, care: { feed: 'Sweets and cuddles', play: 'Roll it gently', note: 'Hums when content.' },
    build: { archetype: 'rodent', skin: 'fur', palette: { base: 0xe87fb0, belly: 0xf0a8cc, tip: 0xc060a0, accent: 0x8a3a6a, eye: 0x201018, spark: 0xffd0e8 },
      body: { len: 0.34, girth: 0.4 }, head: { shape: 'round', size: 0.9 }, eyes: { count: 2, size: 0.13 }, ears: { type: 'none' }, legs: { count: 0, type: 'none' }, tail: { type: 'none' } },
  },
  {
    id: 'gnome', name: 'Garden Gnome', latin: 'Gernumbli gardensi', tier: 'common',
    blurb: 'A small, leathery, potato-headed pest that infests wizarding gardens. Bites.',
    size: 0.55, speed: 1.6, roam: 9, diet: ['leafy_greens', 'beetle', 'berries'], favorite: 'beetle',
    unlockCost: 25, care: { feed: 'Roots and grubs', play: 'It loves to be swung (gently!)', note: 'Cheeky and quick.' },
    build: { archetype: 'humanoid', skin: 'hide', palette: { base: 0xb89a6a, belly: 0xc8aa7c, accent: 0x8a6a3a, eye: 0x2a1a0a, spark: 0xd8c090 },
      body: { len: 0.32, girth: 0.34 }, head: { shape: 'round', size: 1.2 }, eyes: { count: 2, size: 0.1 }, ears: { type: 'point' }, legs: { count: 2, type: 'paw' }, tail: { type: 'none' } },
  },
  {
    id: 'knarl', name: 'Knarl', latin: 'Hystrix knarlus', tier: 'common',
    blurb: 'Indistinguishable from a hedgehog — until you offer it food, which it takes as a trap.',
    size: 0.5, speed: 1.2, roam: 7, diet: ['beetle', 'berries', 'leafy_greens'], favorite: 'beetle',
    produces: { item: 'Knarl quill', amount: 8, every: 75 }, unlockCost: 35,
    care: { feed: 'Leave food and step back', play: 'Earn its prickly trust', note: 'Suspicious of kindness.' },
    build: { archetype: 'rodent', skin: 'fur', palette: { base: 0x5a4a36, belly: 0xc8b48a, accent: 0x3a2e1e, horn: 0x6a5840, eye: 0x100a06, spark: 0xb89a64 },
      body: { len: 0.5, girth: 0.42 }, head: { shape: 'snout', size: 0.8 }, eyes: { count: 2, size: 0.1 }, ears: { type: 'round' }, legs: { count: 4, type: 'paw' }, tail: { type: 'none' }, extras: ['spikes'] },
  },
  {
    id: 'horklump', name: 'Horklump', latin: 'Fungus horklumpus', tier: 'common',
    blurb: 'A fleshy pink mushroom that spreads sinewy tendrils underground. Gnomes adore it.',
    size: 0.45, speed: 0.4, roam: 2, diet: ['leafy_greens', 'beetle'], favorite: 'leafy_greens',
    unlockCost: 20, care: { feed: 'Earthworms', play: 'It does not play', note: 'Multiplies alarmingly.' },
    build: { archetype: 'amorphous', skin: 'smooth', palette: { base: 0xe0a0b0, belly: 0xf0c0cc, accent: 0xb87088, eye: 0x402028, spark: 0xffd8e0 },
      body: { len: 0.4, girth: 0.42 }, head: { shape: 'round', size: 0.7 }, eyes: { count: 2, size: 0.08 }, legs: { count: 0, type: 'none' }, extras: ['shell'] },
  },
  {
    id: 'chizpurfle', name: 'Chizpurfle', latin: 'Parasitus chizpurfle', tier: 'common',
    blurb: 'A tiny crab-like parasite with great fangs, drawn to anything magical.',
    size: 0.4, speed: 1.8, roam: 8, diet: ['beetle', 'gold_coin'], favorite: 'beetle',
    unlockCost: 30, care: { feed: 'Magical residue', play: 'It scuttles', note: 'Keep it off your wand.' },
    build: { archetype: 'arachnid', skin: 'chitin', palette: { base: 0x6a3a2a, belly: 0x8a5a3a, accent: 0x3a1e14, eye: 0xc04020, spark: 0xe08040 },
      body: { len: 0.3, girth: 0.28 }, head: { shape: 'round', size: 0.7 }, eyes: { count: 4, size: 0.06 }, legs: { count: 6, type: 'stick' }, tail: { type: 'none' }, extras: ['antennae'] },
  },

  // ─────────────── UNCOMMON ───────────────
  {
    id: 'bowtruckle', name: 'Bowtruckle', latin: 'Arbori custos', tier: 'uncommon',
    blurb: 'A tiny twig-like tree guardian with knobbly brown eyes, fiercely loyal to its home tree.',
    size: 0.46, speed: 1.1, roam: 6, diet: ['beetle', 'leafy_greens', 'berries'], favorite: 'beetle',
    produces: { item: 'wand-wood sliver', amount: 12, every: 85 }, unlockCost: 130,
    care: { feed: 'Woodlice', play: 'Let it climb your fingers', note: 'Will gouge eyes if its tree is threatened.' },
    build: { archetype: 'plant', skin: 'bark', palette: { base: 0x4a6a32, belly: 0x6a8a44, accent: 0x35501f, eye: 0x2a3a18, spark: 0x9ad17a },
      body: { len: 0.4, girth: 0.18 }, head: { shape: 'round', size: 0.7 }, eyes: { count: 2, size: 0.09 }, legs: { count: 2, type: 'stick' }, tail: { type: 'none' }, extras: ['crest'] },
  },
  {
    id: 'crup', name: 'Crup', latin: 'Canis bifurcus', tier: 'uncommon',
    blurb: 'Like a Jack Russell terrier with a forked tail — utterly devoted to wizards, savage to Muggles.',
    size: 0.7, speed: 1.9, roam: 10, diet: ['raw_meat', 'fresh_fish', 'beetle'], favorite: 'raw_meat',
    produces: { item: 'Crup whisker', amount: 10, every: 80 }, unlockCost: 170,
    care: { feed: 'Meat — even gnomes', play: 'Fetch, endlessly', note: 'The forked tail is its tell.' },
    build: { archetype: 'beast', skin: 'fur', palette: { base: 0x8a5a32, belly: 0xc8a070, accent: 0x5a3a1e, eye: 0x2a1808, spark: 0xd8b488 },
      body: { len: 0.62, girth: 0.4 }, head: { shape: 'snout', size: 0.8 }, eyes: { count: 2, size: 0.13 }, ears: { type: 'point' }, legs: { count: 4, type: 'paw' }, tail: { type: 'plume', len: 0.5 }, extras: ['whiskers'] },
  },
  {
    id: 'jarvey', name: 'Jarvey', latin: 'Mustela loquens', tier: 'uncommon',
    blurb: 'An overgrown ferret that can talk — mostly in short, rude bursts. Hunts gnomes underground.',
    size: 0.6, speed: 1.7, roam: 9, diet: ['raw_meat', 'beetle', 'fresh_fish'], favorite: 'beetle',
    produces: { item: 'Jarvey fur', amount: 11, every: 82 }, unlockCost: 160,
    care: { feed: 'Moles and gnomes', play: 'Trade insults with it', note: 'Sharp tongue, sharper teeth.' },
    build: { archetype: 'beast', skin: 'fur', palette: { base: 0x6a5236, belly: 0xb8a070, accent: 0x42321e, eye: 0x1a1008, spark: 0xc8b088 },
      body: { len: 0.7, girth: 0.3 }, head: { shape: 'snout', size: 0.7 }, eyes: { count: 2, size: 0.11 }, ears: { type: 'round' }, legs: { count: 4, type: 'paw' }, tail: { type: 'tuft', len: 0.5 }, extras: ['whiskers'] },
  },
  {
    id: 'clabbert', name: 'Clabbert', latin: 'Simia ranae', tier: 'uncommon',
    blurb: 'A smooth-skinned tree-dweller, half monkey and half frog, with a pustule that glows red at danger.',
    size: 0.62, speed: 1.5, roam: 8, diet: ['fresh_fish', 'beetle', 'berries'], favorite: 'fresh_fish',
    produces: { item: 'Clabbert pustule', amount: 12, every: 84 }, unlockCost: 190,
    care: { feed: 'Small lizards', play: 'Watch its forehead light up', note: 'The glow warns of intruders.' },
    build: { archetype: 'amphibian', skin: 'smooth', palette: { base: 0x4a8a5a, belly: 0x8ac090, accent: 0x2f5a38, eye: 0xe0c040, spark: 0xff6040 },
      body: { len: 0.6, girth: 0.38 }, head: { shape: 'frog', size: 0.9 }, eyes: { count: 2, size: 0.18 }, legs: { count: 4, type: 'webbed' }, tail: { type: 'none' }, extras: ['gem'] },
  },
  {
    id: 'murtlap', name: 'Murtlap', latin: 'Murtlap marinus', tier: 'uncommon',
    blurb: 'A rat-like marine beast with a growth like a sea anemone on its back, prized in healing.',
    size: 0.55, speed: 1.4, roam: 7, habitat: 'coast', diet: ['fresh_fish', 'beetle'], favorite: 'fresh_fish',
    produces: { item: 'Murtlap tentacle', amount: 13, every: 86 }, unlockCost: 200,
    care: { feed: 'Crustaceans', play: 'Let it paddle', note: 'Its growth pickles into a healing essence.' },
    build: { archetype: 'aquatic', skin: 'smooth', palette: { base: 0x6a6a78, belly: 0x9a9aa8, accent: 0xc06a8a, eye: 0x101018, spark: 0xd88aaa },
      body: { len: 0.6, girth: 0.34 }, head: { shape: 'snout', size: 0.7 }, eyes: { count: 2, size: 0.1 }, ears: { type: 'round' }, legs: { count: 4, type: 'webbed' }, tail: { type: 'lizard', len: 0.5 }, extras: ['frill'] },
  },

  // ─────────────── RARE ───────────────
  {
    id: 'demiguise', name: 'Demiguise', latin: 'Simia invisibilis', tier: 'rare',
    blurb: 'A peaceful, ape-like beast with long silvery hair and great black eyes — it can foresee danger and turn invisible.',
    size: 1.0, speed: 1.2, roam: 8, diet: ['leafy_greens', 'berries', 'honey_pot'], favorite: 'berries', nocturnal: true,
    produces: { item: 'Demiguise hair', amount: 16, every: 95 }, unlockCost: 360,
    care: { feed: 'Fruit, quietly', play: 'You must surprise it — it sees you coming', note: 'Its pelt makes Invisibility Cloaks.' },
    build: { archetype: 'humanoid', skin: 'fur', palette: { base: 0xc8c4bc, belly: 0xe0ddd6, tip: 0xa8a49c, accent: 0x9a968e, eye: 0x0a0a0e, spark: 0xeae6dc },
      body: { len: 0.5, girth: 0.4 }, head: { shape: 'round', size: 1.0 }, eyes: { count: 2, size: 0.24, glow: false }, ears: { type: 'round' }, legs: { count: 2, type: 'paw' }, tail: { type: 'none' }, extras: ['mane', 'wisps'] },
  },
  {
    id: 'occamy', name: 'Occamy', latin: 'Serpens plumatus', tier: 'rare',
    blurb: 'A plumed, winged serpent of silver-blue feather and scale that grows or shrinks to fit any space.',
    size: 1.2, speed: 1.6, roam: 9, diet: ['beetle', 'fresh_fish', 'raw_meat'], favorite: 'beetle',
    produces: { item: 'Occamy eggshell (silver)', amount: 20, every: 105 }, unlockCost: 460,
    care: { feed: 'Insects & rodents', play: 'Give it room to coil', note: 'Choranaptyxic — fills the space it is in.' },
    build: { archetype: 'serpent', skin: 'feather', palette: { base: 0x3a7aa8, belly: 0x9ac8e0, accent: 0x2a5a88, horn: 0xc8d8e8, eye: 0xe0a040, spark: 0xbfe0f8, wing: 0x4a8ab8 },
      body: { len: 0.9, girth: 0.3 }, head: { shape: 'draconic', size: 0.8 }, eyes: { count: 2, size: 0.13 }, wings: { type: 'feather', span: 1.0 }, legs: { count: 0, type: 'none' }, tail: { type: 'serpent', len: 0.7 }, extras: ['crest'] },
  },
  {
    id: 'billywig', name: 'Billywig', latin: 'Insectum vertiginis', tier: 'rare',
    blurb: 'A vivid sapphire Australian insect whose sting causes giddiness and floating. Its dried stings are sweets.',
    size: 0.5, speed: 2.2, roam: 11, diet: ['berries', 'honey_pot', 'beetle'], favorite: 'honey_pot',
    produces: { item: 'Billywig sting', amount: 18, every: 90 }, unlockCost: 380,
    care: { feed: 'Nectar', play: 'Chase its spinning flight', note: 'A sting brings giddiness, then floating.' },
    build: { archetype: 'insectoid', skin: 'chitin', palette: { base: 0x2a5ad0, belly: 0x5a8af0, accent: 0x8ac0ff, horn: 0xffd060, eye: 0x101030, spark: 0x9ac8ff, wing: 0xbfe0ff },
      body: { len: 0.4, girth: 0.26 }, head: { shape: 'round', size: 0.8 }, eyes: { count: 2, size: 0.12 }, wings: { type: 'insect', span: 0.7 }, legs: { count: 6, type: 'stick' }, tail: { type: 'scorpion', len: 0.4 }, extras: ['antennae'] },
  },
  {
    id: 'augurey', name: 'Augurey', latin: 'Avis lacrimosa', tier: 'rare',
    blurb: 'The Irish Phoenix: a thin, mournful greenish-black bird whose cry was once thought to foretell death.',
    size: 0.9, speed: 1.5, roam: 9, habitat: 'forest', diet: ['beetle', 'fresh_fish', 'berries'], favorite: 'beetle', nocturnal: true,
    produces: { item: 'Augurey feather', amount: 15, every: 92 }, unlockCost: 340,
    care: { feed: 'Insects & fae', play: 'Soothe its sorrowful song', note: 'It cries only before rain.' },
    build: { archetype: 'avian', skin: 'feather', palette: { base: 0x2a3a30, belly: 0x3e5446, accent: 0x1a2820, horn: 0x3a3a2a, eye: 0x806020, spark: 0x6a8a70 },
      body: { len: 0.6, girth: 0.34 }, head: { shape: 'beak', size: 0.8 }, eyes: { count: 2, size: 0.12 }, wings: { type: 'feather', span: 1.1 }, legs: { count: 2, type: 'talon' }, tail: { type: 'plume', len: 0.6 } },
  },

  // ─────────────── ULTRA RARE ───────────────
  {
    id: 'erumpent', name: 'Erumpent', latin: 'Rhinoceros eruptus', tier: 'ultra',
    blurb: 'A massive African beast like a rhinoceros, with a single great horn of explosive fluid. Charges when in love.',
    size: 1.7, speed: 1.0, roam: 7, diet: ['leafy_greens', 'raw_meat'], favorite: 'leafy_greens',
    produces: { item: 'Erumpent fluid', amount: 26, every: 120 }, unlockCost: 720,
    care: { feed: 'Grasses, in bulk', play: 'Mind the horn — everything it pierces explodes', note: 'Thick hide turns most spells.' },
    build: { archetype: 'beast', skin: 'hide', palette: { base: 0x8a7a64, belly: 0xa89a82, accent: 0x5a4e3e, horn: 0xe8e0c8, eye: 0x2a1e10, spark: 0xffcf80 },
      body: { len: 0.9, girth: 0.62, hump: true }, head: { shape: 'snout', size: 1.0 }, eyes: { count: 2, size: 0.12 }, ears: { type: 'round' }, horns: { type: 'single', size: 0.4 }, legs: { count: 4, type: 'hoof' }, tail: { type: 'tuft', len: 0.5 } },
  },
  {
    id: 'snallygaster', name: 'Snallygaster', latin: 'Draco avianus', tier: 'ultra',
    blurb: 'A part-bird, part-reptile American beast with metallic scales and a single dangerous fang.',
    size: 1.4, speed: 1.5, roam: 9, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat',
    produces: { item: 'Snallygaster scale', amount: 24, every: 112 }, unlockCost: 640,
    care: { feed: 'Whole carcasses', play: 'Earn its grudging trust', note: 'Loves shiny machinery.' },
    build: { archetype: 'dragon', skin: 'scale', palette: { base: 0x4a5a4a, belly: 0x7a8a6a, accent: 0x2e3a2e, horn: 0xc8c0a0, eye: 0xc05030, spark: 0xa0b890, wing: 0x3a4a3a },
      body: { len: 0.85, girth: 0.5 }, head: { shape: 'beak', size: 0.9 }, eyes: { count: 2, size: 0.12 }, wings: { type: 'bat', span: 1.2 }, legs: { count: 2, type: 'talon' }, tail: { type: 'lizard', len: 0.8 }, extras: ['spikes'] },
  },
  {
    id: 'reem', name: 'Re\'em', latin: 'Bos aureus', tier: 'ultra',
    blurb: 'A gigantic golden-skinned ox of immense strength; its blood grants whoever drinks it tremendous power.',
    size: 1.6, speed: 1.1, roam: 8, diet: ['leafy_greens', 'honey_pot', 'berries'], favorite: 'leafy_greens',
    produces: { item: 'Re\'em hair', amount: 25, every: 115 }, unlockCost: 700,
    care: { feed: 'Golden grasses', play: 'Walk beside its quiet power', note: 'Exceedingly rare; immensely strong.' },
    build: { archetype: 'beast', skin: 'hide', palette: { base: 0xc8a24a, belly: 0xe0c478, accent: 0x9a7a2e, horn: 0xf0e0b0, eye: 0x3a2a10, spark: 0xffe69a },
      body: { len: 0.95, girth: 0.6, hump: true }, head: { shape: 'snout', size: 0.95 }, eyes: { count: 2, size: 0.12 }, ears: { type: 'round' }, horns: { type: 'pair', size: 0.32 }, legs: { count: 4, type: 'hoof' }, tail: { type: 'tuft', len: 0.6 } },
  },
  {
    id: 'manticore', name: 'Manticore', latin: 'Manticora venenata', tier: 'ultra',
    blurb: 'A fearsome beast with the body of a lion, a scorpion\'s tail and a near-human head. Its sting kills instantly.',
    size: 1.5, speed: 1.6, roam: 9, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat', nocturnal: true,
    produces: { item: 'Manticore venom', amount: 28, every: 125 }, unlockCost: 820,
    care: { feed: 'Fresh meat, much of it', play: 'Never turn your back', note: 'It croons softly as it devours prey.' },
    build: { archetype: 'beast', skin: 'fur', palette: { base: 0x9a5a32, belly: 0xc89060, accent: 0x6a3a1e, horn: 0x3a2a1a, eye: 0xd0a030, spark: 0xc8504a },
      body: { len: 0.85, girth: 0.5 }, head: { shape: 'feline', size: 0.95 }, eyes: { count: 2, size: 0.14 }, ears: { type: 'round' }, legs: { count: 4, type: 'paw' }, tail: { type: 'scorpion', len: 0.7 }, extras: ['mane', 'whiskers'] },
  },

  // ─────────────── LEGENDARY ───────────────
  {
    id: 'nundu', name: 'Nundu', latin: 'Panthera pestifera', tier: 'legendary',
    blurb: 'A gigantic leopard that moves in silence; its breath carries disease enough to wipe out a village. The deadliest beast alive.',
    size: 1.8, speed: 1.4, roam: 9, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat', nocturnal: true,
    produces: { item: 'Nundu whisker', amount: 34, every: 140 }, unlockCost: 1400,
    care: { feed: 'Whole beasts', play: 'It takes a hundred wizards to subdue — and your trust to befriend', note: 'Steps without a sound.' },
    build: { archetype: 'beast', skin: 'fur', palette: { base: 0xb89a5a, belly: 0xe0cc94, accent: 0x6a5028, eye: 0xe0b030, spark: 0xa0d090, pattern: 'spots' },
      body: { len: 0.95, girth: 0.56 }, head: { shape: 'feline', size: 1.0 }, eyes: { count: 2, size: 0.15 }, ears: { type: 'round' }, legs: { count: 4, type: 'paw' }, tail: { type: 'tuft', len: 0.85 }, extras: ['whiskers', 'frill'] },
  },
  {
    id: 'basilisk', name: 'Basilisk', latin: 'Serpens rex', tier: 'legendary',
    blurb: 'The King of Serpents — a colossal green snake whose direct gaze brings instant death and whose venom is without rival.',
    size: 1.9, speed: 1.2, roam: 8, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat', nocturnal: true,
    produces: { item: 'Basilisk venom', amount: 40, every: 150 }, unlockCost: 1800,
    care: { feed: 'Spiders flee it; feed it meat', play: 'Approach with eyes averted', note: 'Hatched from a chicken\'s egg beneath a toad.' },
    build: { archetype: 'serpent', skin: 'scale', palette: { base: 0x2a6a2a, belly: 0x6aa84a, accent: 0x1a4a1a, horn: 0xd8c060, eye: 0xe0c030, spark: 0xa0e060 },
      body: { len: 1.3, girth: 0.42 }, head: { shape: 'draconic', size: 1.0 }, eyes: { count: 2, size: 0.16, glow: true }, legs: { count: 0, type: 'none' }, tail: { type: 'serpent', len: 1.0 }, extras: ['crest', 'spikes'] },
  },
  {
    id: 'horntail', name: 'Hungarian Horntail', latin: 'Draco horridus', tier: 'legendary',
    blurb: 'The most dangerous breed of dragon — black-scaled, bronze-horned, with a spiked tail and a forty-foot jet of flame.',
    size: 1.9, speed: 1.5, roam: 10, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat',
    produces: { item: 'dragon scale', amount: 44, every: 155 }, unlockCost: 2200,
    care: { feed: 'Whole cattle', play: 'Keep well clear of the flame', note: 'Yellow eyes, bronze horns, a tail of spikes.' },
    build: { archetype: 'dragon', skin: 'scale', palette: { base: 0x1e1e22, belly: 0x4a3a1a, accent: 0x2e2e34, horn: 0xb8923a, eye: 0xe0c030, spark: 0xff7030, wing: 0x18181c },
      body: { len: 1.0, girth: 0.6 }, head: { shape: 'draconic', size: 1.0 }, eyes: { count: 2, size: 0.14, glow: true }, horns: { type: 'pair', size: 0.34 }, wings: { type: 'bat', span: 1.6 }, legs: { count: 4, type: 'talon' }, tail: { type: 'scorpion', len: 1.0 }, extras: ['spikes', 'tusks'] },
  },

  // ─────────────── MYTHIC ───────────────
  {
    id: 'phoenix', name: 'Phoenix', latin: 'Avis renata', tier: 'mythic',
    blurb: 'A swan-sized scarlet bird with a golden tail, born again from its own ashes. Its tears heal; its song gives heart.',
    size: 1.2, speed: 1.7, roam: 10, diet: ['berries', 'honey_pot', 'gourmet_treat'], favorite: 'honey_pot',
    produces: { item: 'phoenix feather', amount: 50, every: 160 }, unlockCost: 3000,
    care: { feed: 'Sweet fruit & sunlight', play: 'Let its song lift your heart', note: 'Bursts to flame and rises from the ash.' },
    build: { archetype: 'avian', skin: 'feather', palette: { base: 0xd83a1a, belly: 0xf07030, accent: 0xf0c040, horn: 0xffd860, eye: 0x402000, spark: 0xffd040, wing: 0xe85a20 },
      body: { len: 0.7, girth: 0.36 }, head: { shape: 'beak', size: 0.85 }, eyes: { count: 2, size: 0.13, glow: true }, wings: { type: 'feather', span: 1.4 }, legs: { count: 2, type: 'talon' }, tail: { type: 'plume', len: 1.1 }, extras: ['crest', 'wisps'] },
  },
  {
    id: 'thunderbird', name: 'Thunderbird', latin: 'Avis tempestatis', tier: 'mythic',
    blurb: 'A great American bird with many wings that shimmer with cloud and sun; it senses danger and brews storms as it flies.',
    size: 1.6, speed: 1.8, roam: 11, diet: ['fresh_fish', 'raw_meat', 'gourmet_treat'], favorite: 'fresh_fish',
    produces: { item: 'thunderbird feather', amount: 52, every: 165 }, unlockCost: 3200,
    care: { feed: 'Fish from on high', play: 'Fly with it through the storm it makes', note: 'Each wing-beat rolls thunder.' },
    build: { archetype: 'avian', skin: 'feather', palette: { base: 0x8a6a3a, belly: 0xd8c088, accent: 0xf0e0b0, horn: 0xe0c060, eye: 0x402810, spark: 0xffe79a, wing: 0xa88a52 },
      body: { len: 0.85, girth: 0.42 }, head: { shape: 'beak', size: 0.9 }, eyes: { count: 2, size: 0.13, glow: true }, wings: { type: 'feather', span: 1.7 }, legs: { count: 2, type: 'talon' }, tail: { type: 'plume', len: 0.9 }, extras: ['crest'] },
  },
  {
    id: 'sphinx', name: 'Sphinx', latin: 'Sphinx aenigmatica', tier: 'mythic',
    blurb: 'A beast with the body of a great lion and the head of a woman, who guards treasures and speaks only in riddles.',
    size: 1.5, speed: 1.3, roam: 8, diet: ['raw_meat', 'honey_pot', 'gourmet_treat'], favorite: 'honey_pot',
    produces: { item: 'sphinx riddle', amount: 46, every: 150 }, unlockCost: 2800,
    care: { feed: 'Fine food & finer questions', play: 'Answer its riddle correctly', note: 'Violent only when its riddle is failed.' },
    build: { archetype: 'beast', skin: 'fur', palette: { base: 0xc8a45a, belly: 0xe0c890, accent: 0x8a6a30, horn: 0x4a3a1e, eye: 0x3a2a10, spark: 0xffe09a },
      body: { len: 0.9, girth: 0.52 }, head: { shape: 'round', size: 1.0 }, eyes: { count: 2, size: 0.15 }, ears: { type: 'round' }, legs: { count: 4, type: 'paw' }, tail: { type: 'tuft', len: 0.8 }, extras: ['mane'] },
  },
  {
    id: 'runespoor', name: 'Runespoor', latin: 'Serpens tricephalus', tier: 'mythic',
    blurb: 'A striking orange-and-black serpent with three heads — the Planner, the Dreamer and the Critic, forever bickering.',
    size: 1.3, speed: 1.3, roam: 8, diet: ['raw_meat', 'beetle', 'fresh_fish'], favorite: 'raw_meat', nocturnal: true,
    produces: { item: 'Runespoor egg', amount: 42, every: 145 }, unlockCost: 2600,
    care: { feed: 'Small mammals', play: 'Settle its three squabbling heads', note: 'Three heads rarely agree on anything.' },
    build: { archetype: 'serpent', skin: 'scale', palette: { base: 0xd86a20, belly: 0xf0a050, accent: 0x1a1a1a, horn: 0x2a2a2a, eye: 0xe0d020, spark: 0xffb060, pattern: 'stripes' },
      body: { len: 1.0, girth: 0.34 }, head: { shape: 'draconic', size: 0.85 }, eyes: { count: 2, size: 0.13, glow: true }, legs: { count: 0, type: 'none' }, tail: { type: 'serpent', len: 0.8 } },
  },
];
