// ─────────────────────────────────────────────────────────────────────────────
//  specs.js — data-driven creatures. Each is a compact parametric spec fed to
//  builder.js. Designed to be canon-accurate and visually distinct: archetype,
//  skin, palette and parts are chosen so every beast is recognisable on sight.
//  Tiers: common · uncommon · rare · ultra · legendary · mythic.
// ─────────────────────────────────────────────────────────────────────────────

const P = (o) => o; // tiny helper for readability

export const SPECS = [
  // ─────────────── COMMON ───────────────
  {
    id: 'flobberworm', name: 'Flobberworm', latin: 'Vermis flobberus', tier: 'common',
    blurb: 'A toothless brown worm that does little but eat lettuce. Utterly placid.',
    size: 0.5, speed: 0.7, roam: 4, diet: ['leafy_greens', 'berries'], favorite: 'leafy_greens',
    produces: { item: 'Flobber-mucus', amount: 6, every: 70 }, unlockCost: 30,
    care: { feed: 'Lettuce, endlessly', play: 'It mostly just lies there', note: 'The easiest beast to keep alive.' },
    build: { archetype: 'serpent', skin: 'smooth', palette: { base: 0x7a5a3a, belly: 0x9a7a52, accent: 0x5a4028, eye: 0x201810, spark: 0xbda47a },
      body: { len: 0.7, girth: 0.22 }, head: { shape: 'round', size: 0.5 }, eyes: { count: 2, size: 0.07 }, legs: { count: 0, type: 'none' }, tail: { type: 'serpent', len: 0.5 } },
  },
  {
    id: 'pygmypuff', name: 'Pygmy Puff', latin: 'Puffus pygmaeus', tier: 'common',
    blurb: 'A miniature Puffskein bred by the Weasley twins — a humming ball of pink or purple fluff.',
    size: 0.42, speed: 1.0, roam: 5, diet: ['sweet_truffle', 'honey_pot', 'berries'], favorite: 'sweet_truffle',
    unlockCost: 40, care: { feed: 'Sweets and cuddles', play: 'Roll it gently', note: 'Hums when content.' },
    build: { archetype: 'rodent', skin: 'fur', palette: { base: 0xe87fb0, belly: 0xf0a8cc, tip: 0xc060a0, accent: 0x8a3a6a, eye: 0x201018, spark: 0xffd0e8 },
      body: { len: 0.34, girth: 0.4 }, head: { shape: 'round', size: 0.9 }, eyes: { count: 2, size: 0.13 }, ears: { type: 'none' }, legs: { count: 0, type: 'none' }, tail: { type: 'none' } },
  },
  {
    id: 'gnome', name: 'Garden Gnome', latin: 'Gernumbli gardensi', tier: 'common',
    blurb: 'A small, leathery, potato-headed pest that infests wizarding gardens. Bites.',
    size: 0.55, speed: 1.6, roam: 9, diet: ['leafy_greens', 'beetle', 'berries'], favorite: 'beetle',
    unlockCost: 25, care: { feed: 'Roots and grubs', play: 'It loves to be swung (gently!)', note: 'Cheeky and quick.' },
    build: { archetype: 'humanoid', skin: 'hide', palette: { base: 0xb89a6a, belly: 0xc8aa7c, accent: 0x8a6a3a, eye: 0x2a1a0a, spark: 0xd8c090 },
      body: { len: 0.32, girth: 0.34 }, head: { shape: 'round', size: 1.2 }, eyes: { count: 2, size: 0.1 }, ears: { type: 'point' }, legs: { count: 2, type: 'paw' }, tail: { type: 'none' } },
  },
  {
    id: 'knarl', name: 'Knarl', latin: 'Hystrix knarlus', tier: 'common',
    blurb: 'Indistinguishable from a hedgehog — until you offer it food, which it takes as a trap.',
    size: 0.5, speed: 1.2, roam: 7, diet: ['beetle', 'berries', 'leafy_greens'], favorite: 'beetle',
    produces: { item: 'Knarl quill', amount: 8, every: 75 }, unlockCost: 35,
    care: { feed: 'Leave food and step back', play: 'Earn its prickly trust', note: 'Suspicious of kindness.' },
    build: { archetype: 'rodent', skin: 'fur', palette: { base: 0x5a4a36, belly: 0xc8b48a, accent: 0x3a2e1e, horn: 0x6a5840, eye: 0x100a06, spark: 0xb89a64 },
      body: { len: 0.5, girth: 0.42 }, head: { shape: 'snout', size: 0.8 }, eyes: { count: 2, size: 0.1 }, ears: { type: 'round' }, legs: { count: 4, type: 'paw' }, tail: { type: 'none' }, extras: ['spikes'] },
  },
  {
    id: 'horklump', name: 'Horklump', latin: 'Fungus horklumpus', tier: 'common',
    blurb: 'A fleshy pink mushroom that spreads sinewy tendrils underground. Gnomes adore it.',
    size: 0.45, speed: 0.4, roam: 2, diet: ['leafy_greens', 'beetle'], favorite: 'leafy_greens',
    unlockCost: 20, care: { feed: 'Earthworms', play: 'It does not play', note: 'Multiplies alarmingly.' },
    build: { archetype: 'amorphous', skin: 'smooth', palette: { base: 0xe0a0b0, belly: 0xf0c0cc, accent: 0xb87088, eye: 0x402028, spark: 0xffd8e0 },
      body: { len: 0.4, girth: 0.42 }, head: { shape: 'round', size: 0.7 }, eyes: { count: 2, size: 0.08 }, legs: { count: 0, type: 'none' }, extras: ['shell'] },
  },
  {
    id: 'chizpurfle', name: 'Chizpurfle', latin: 'Parasitus chizpurfle', tier: 'common',
    blurb: 'A tiny crab-like parasite with great fangs, drawn to anything magical.',
    size: 0.4, speed: 1.8, roam: 8, diet: ['beetle', 'gold_coin'], favorite: 'beetle',
    unlockCost: 30, care: { feed: 'Magical residue', play: 'It scuttles', note: 'Keep it off your wand.' },
    build: { archetype: 'arachnid', skin: 'chitin', palette: { base: 0x6a3a2a, belly: 0x8a5a3a, accent: 0x3a1e14, eye: 0xc04020, spark: 0xe08040 },
      body: { len: 0.3, girth: 0.28 }, head: { shape: 'round', size: 0.7 }, eyes: { count: 4, size: 0.06 }, legs: { count: 6, type: 'stick' }, tail: { type: 'none' }, extras: ['antennae'] },
  },

  // ─────────────── UNCOMMON ───────────────
  {
    id: 'bowtruckle', name: 'Bowtruckle', latin: 'Arbori custos', tier: 'uncommon',
    blurb: 'A tiny twig-like tree guardian with knobbly brown eyes, fiercely loyal to its home tree.',
    size: 0.46, speed: 1.1, roam: 6, diet: ['beetle', 'leafy_greens', 'berries'], favorite: 'beetle',
    produces: { item: 'wand-wood sliver', amount: 12, every: 85 }, unlockCost: 130,
    care: { feed: 'Woodlice', play: 'Let it climb your fingers', note: 'Will gouge eyes if its tree is threatened.' },
    build: { archetype: 'plant', skin: 'bark', palette: { base: 0x4a6a32, belly: 0x6a8a44, accent: 0x35501f, eye: 0x2a3a18, spark: 0x9ad17a },
      body: { len: 0.4, girth: 0.18 }, head: { shape: 'round', size: 0.7 }, eyes: { count: 2, size: 0.09 }, legs: { count: 2, type: 'stick' }, tail: { type: 'none' }, extras: ['crest'] },
  },
  {
    id: 'crup', name: 'Crup', latin: 'Canis bifurcus', tier: 'uncommon',
    blurb: 'Like a Jack Russell terrier with a forked tail — utterly devoted to wizards, savage to Muggles.',
    size: 0.7, speed: 1.9, roam: 10, diet: ['raw_meat', 'fresh_fish', 'beetle'], favorite: 'raw_meat',
    produces: { item: 'Crup whisker', amount: 10, every: 80 }, unlockCost: 170,
    care: { feed: 'Meat — even gnomes', play: 'Fetch, endlessly', note: 'The forked tail is its tell.' },
    build: { archetype: 'beast', skin: 'fur', palette: { base: 0x8a5a32, belly: 0xc8a070, accent: 0x5a3a1e, eye: 0x2a1808, spark: 0xd8b488 },
      body: { len: 0.62, girth: 0.4 }, head: { shape: 'snout', size: 0.8 }, eyes: { count: 2, size: 0.13 }, ears: { type: 'point' }, legs: { count: 4, type: 'paw' }, tail: { type: 'plume', len: 0.5 }, extras: ['whiskers'] },
  },
  {
    id: 'jarvey', name: 'Jarvey', latin: 'Mustela loquens', tier: 'uncommon',
    blurb: 'An overgrown ferret that can talk — mostly in short, rude bursts. Hunts gnomes underground.',
    size: 0.6, speed: 1.7, roam: 9, diet: ['raw_meat', 'beetle', 'fresh_fish'], favorite: 'beetle',
    produces: { item: 'Jarvey fur', amount: 11, every: 82 }, unlockCost: 160,
    care: { feed: 'Moles and gnomes', play: 'Trade insults with it', note: 'Sharp tongue, sharper teeth.' },
    build: { archetype: 'beast', skin: 'fur', palette: { base: 0x6a5236, belly: 0xb8a070, accent: 0x42321e, eye: 0x1a1008, spark: 0xc8b088 },
      body: { len: 0.7, girth: 0.3 }, head: { shape: 'snout', size: 0.7 }, eyes: { count: 2, size: 0.11 }, ears: { type: 'round' }, legs: { count: 4, type: 'paw' }, tail: { type: 'tuft', len: 0.5 }, extras: ['whiskers'] },
  },
  {
    id: 'clabbert', name: 'Clabbert', latin: 'Simia ranae', tier: 'uncommon',
    blurb: 'A smooth-skinned tree-dweller, half monkey and half frog, with a pustule that glows red at danger.',
    size: 0.62, speed: 1.5, roam: 8, diet: ['fresh_fish', 'beetle', 'berries'], favorite: 'fresh_fish',
    produces: { item: 'Clabbert pustule', amount: 12, every: 84 }, unlockCost: 190,
    care: { feed: 'Small lizards', play: 'Watch its forehead light up', note: 'The glow warns of intruders.' },
    build: { archetype: 'amphibian', skin: 'smooth', palette: { base: 0x4a8a5a, belly: 0x8ac090, accent: 0x2f5a38, eye: 0xe0c040, spark: 0xff6040 },
      body: { len: 0.6, girth: 0.38 }, head: { shape: 'frog', size: 0.9 }, eyes: { count: 2, size: 0.18 }, legs: { count: 4, type: 'webbed' }, tail: { type: 'none' }, extras: ['gem'] },
  },
  {
    id: 'murtlap', name: 'Murtlap', latin: 'Murtlap marinus', tier: 'uncommon',
    blurb: 'A rat-like marine beast with a growth like a sea anemone on its back, prized in healing.',
    size: 0.55, speed: 1.4, roam: 7, habitat: 'coast', diet: ['fresh_fish', 'beetle'], favorite: 'fresh_fish',
    produces: { item: 'Murtlap tentacle', amount: 13, every: 86 }, unlockCost: 200,
    care: { feed: 'Crustaceans', play: 'Let it paddle', note: 'Its growth pickles into a healing essence.' },
    build: { archetype: 'aquatic', skin: 'smooth', palette: { base: 0x6a6a78, belly: 0x9a9aa8, accent: 0xc06a8a, eye: 0x101018, spark: 0xd88aaa },
      body: { len: 0.6, girth: 0.34 }, head: { shape: 'snout', size: 0.7 }, eyes: { count: 2, size: 0.1 }, ears: { type: 'round' }, legs: { count: 4, type: 'webbed' }, tail: { type: 'lizard', len: 0.5 }, extras: ['frill'] },
  },

  // ─────────────── RARE ───────────────
  {
    id: 'demiguise', name: 'Demiguise', latin: 'Simia invisibilis', tier: 'rare',
    blurb: 'A peaceful, ape-like beast with long silvery hair and great black eyes — it can foresee danger and turn invisible.',
    size: 1.0, speed: 1.2, roam: 8, diet: ['leafy_greens', 'berries', 'honey_pot'], favorite: 'berries', nocturnal: true,
    produces: { item: 'Demiguise hair', amount: 16, every: 95 }, unlockCost: 360,
    care: { feed: 'Fruit, quietly', play: 'You must surprise it — it sees you coming', note: 'Its pelt makes Invisibility Cloaks.' },
    build: { archetype: 'humanoid', skin: 'fur', palette: { base: 0xc8c4bc, belly: 0xe0ddd6, tip: 0xa8a49c, accent: 0x9a968e, eye: 0x0a0a0e, spark: 0xeae6dc },
      body: { len: 0.5, girth: 0.4 }, head: { shape: 'round', size: 1.0 }, eyes: { count: 2, size: 0.24, glow: false }, ears: { type: 'round' }, legs: { count: 2, type: 'paw' }, tail: { type: 'none' }, extras: ['mane', 'wisps'] },
  },
  {
    id: 'occamy', name: 'Occamy', latin: 'Serpens plumatus', tier: 'rare',
    blurb: 'A plumed, winged serpent of silver-blue feather and scale that grows or shrinks to fit any space.',
    size: 1.2, speed: 1.6, roam: 9, diet: ['beetle', 'fresh_fish', 'raw_meat'], favorite: 'beetle',
    produces: { item: 'Occamy eggshell (silver)', amount: 20, every: 105 }, unlockCost: 460,
    care: { feed: 'Insects & rodents', play: 'Give it room to coil', note: 'Choranaptyxic — fills the space it is in.' },
    build: { archetype: 'serpent', skin: 'feather', palette: { base: 0x3a7aa8, belly: 0x9ac8e0, accent: 0x2a5a88, horn: 0xc8d8e8, eye: 0xe0a040, spark: 0xbfe0f8, wing: 0x4a8ab8 },
      body: { len: 0.9, girth: 0.3 }, head: { shape: 'draconic', size: 0.8 }, eyes: { count: 2, size: 0.13 }, wings: { type: 'feather', span: 1.0 }, legs: { count: 0, type: 'none' }, tail: { type: 'serpent', len: 0.7 }, extras: ['crest'] },
  },
  {
    id: 'billywig', name: 'Billywig', latin: 'Insectum vertiginis', tier: 'rare',
    blurb: 'A vivid sapphire Australian insect whose sting causes giddiness and floating. Its dried stings are sweets.',
    size: 0.5, speed: 2.2, roam: 11, diet: ['berries', 'honey_pot', 'beetle'], favorite: 'honey_pot',
    produces: { item: 'Billywig sting', amount: 18, every: 90 }, unlockCost: 380,
    care: { feed: 'Nectar', play: 'Chase its spinning flight', note: 'A sting brings giddiness, then floating.' },
    build: { archetype: 'insectoid', skin: 'chitin', palette: { base: 0x2a5ad0, belly: 0x5a8af0, accent: 0x8ac0ff, horn: 0xffd060, eye: 0x101030, spark: 0x9ac8ff, wing: 0xbfe0ff },
      body: { len: 0.4, girth: 0.26 }, head: { shape: 'round', size: 0.8 }, eyes: { count: 2, size: 0.12 }, wings: { type: 'insect', span: 0.7 }, legs: { count: 6, type: 'stick' }, tail: { type: 'scorpion', len: 0.4 }, extras: ['antennae'] },
  },
  {
    id: 'augurey', name: 'Augurey', latin: 'Avis lacrimosa', tier: 'rare',
    blurb: 'The Irish Phoenix: a thin, mournful greenish-black bird whose cry was once thought to foretell death.',
    size: 0.9, speed: 1.5, roam: 9, habitat: 'forest', diet: ['beetle', 'fresh_fish', 'berries'], favorite: 'beetle', nocturnal: true,
    produces: { item: 'Augurey feather', amount: 15, every: 92 }, unlockCost: 340,
    care: { feed: 'Insects & fae', play: 'Soothe its sorrowful song', note: 'It cries only before rain.' },
    build: { archetype: 'avian', skin: 'feather', palette: { base: 0x2a3a30, belly: 0x3e5446, accent: 0x1a2820, horn: 0x3a3a2a, eye: 0x806020, spark: 0x6a8a70 },
      body: { len: 0.6, girth: 0.34 }, head: { shape: 'beak', size: 0.8 }, eyes: { count: 2, size: 0.12 }, wings: { type: 'feather', span: 1.1 }, legs: { count: 2, type: 'talon' }, tail: { type: 'plume', len: 0.6 } },
  },

  // ─────────────── ULTRA RARE ───────────────
  {
    id: 'erumpent', name: 'Erumpent', latin: 'Rhinoceros eruptus', tier: 'ultra',
    blurb: 'A massive African beast like a rhinoceros, with a single great horn of explosive fluid. Charges when in love.',
    size: 1.7, speed: 1.0, roam: 7, diet: ['leafy_greens', 'raw_meat'], favorite: 'leafy_greens',
    produces: { item: 'Erumpent fluid', amount: 26, every: 120 }, unlockCost: 720,
    care: { feed: 'Grasses, in bulk', play: 'Mind the horn — everything it pierces explodes', note: 'Thick hide turns most spells.' },
    build: { archetype: 'beast', skin: 'hide', palette: { base: 0x8a7a64, belly: 0xa89a82, accent: 0x5a4e3e, horn: 0xe8e0c8, eye: 0x2a1e10, spark: 0xffcf80 },
      body: { len: 0.9, girth: 0.62, hump: true }, head: { shape: 'snout', size: 1.0 }, eyes: { count: 2, size: 0.12 }, ears: { type: 'round' }, horns: { type: 'single', size: 0.4 }, legs: { count: 4, type: 'hoof' }, tail: { type: 'tuft', len: 0.5 } },
  },
  {
    id: 'snallygaster', name: 'Snallygaster', latin: 'Draco avianus', tier: 'ultra',
    blurb: 'A part-bird, part-reptile American beast with metallic scales and a single dangerous fang.',
    size: 1.4, speed: 1.5, roam: 9, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat',
    produces: { item: 'Snallygaster scale', amount: 24, every: 112 }, unlockCost: 640,
    care: { feed: 'Whole carcasses', play: 'Earn its grudging trust', note: 'Loves shiny machinery.' },
    build: { archetype: 'dragon', skin: 'scale', palette: { base: 0x4a5a4a, belly: 0x7a8a6a, accent: 0x2e3a2e, horn: 0xc8c0a0, eye: 0xc05030, spark: 0xa0b890, wing: 0x3a4a3a },
      body: { len: 0.85, girth: 0.5 }, head: { shape: 'beak', size: 0.9 }, eyes: { count: 2, size: 0.12 }, wings: { type: 'bat', span: 1.2 }, legs: { count: 2, type: 'talon' }, tail: { type: 'lizard', len: 0.8 }, extras: ['spikes'] },
  },
  {
    id: 'reem', name: 'Re\'em', latin: 'Bos aureus', tier: 'ultra',
    blurb: 'A gigantic golden-skinned ox of immense strength; its blood grants whoever drinks it tremendous power.',
    size: 1.6, speed: 1.1, roam: 8, diet: ['leafy_greens', 'honey_pot', 'berries'], favorite: 'leafy_greens',
    produces: { item: 'Re\'em hair', amount: 25, every: 115 }, unlockCost: 700,
    care: { feed: 'Golden grasses', play: 'Walk beside its quiet power', note: 'Exceedingly rare; immensely strong.' },
    build: { archetype: 'beast', skin: 'hide', palette: { base: 0xc8a24a, belly: 0xe0c478, accent: 0x9a7a2e, horn: 0xf0e0b0, eye: 0x3a2a10, spark: 0xffe69a },
      body: { len: 0.95, girth: 0.6, hump: true }, head: { shape: 'snout', size: 0.95 }, eyes: { count: 2, size: 0.12 }, ears: { type: 'round' }, horns: { type: 'pair', size: 0.32 }, legs: { count: 4, type: 'hoof' }, tail: { type: 'tuft', len: 0.6 } },
  },
  {
    id: 'manticore', name: 'Manticore', latin: 'Manticora venenata', tier: 'ultra',
    blurb: 'A fearsome beast with the body of a lion, a scorpion\'s tail and a near-human head. Its sting kills instantly.',
    size: 1.5, speed: 1.6, roam: 9, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat', nocturnal: true,
    produces: { item: 'Manticore venom', amount: 28, every: 125 }, unlockCost: 820,
    care: { feed: 'Fresh meat, much of it', play: 'Never turn your back', note: 'It croons softly as it devours prey.' },
    build: { archetype: 'beast', skin: 'fur', palette: { base: 0x9a5a32, belly: 0xc89060, accent: 0x6a3a1e, horn: 0x3a2a1a, eye: 0xd0a030, spark: 0xc8504a },
      body: { len: 0.85, girth: 0.5 }, head: { shape: 'feline', size: 0.95 }, eyes: { count: 2, size: 0.14 }, ears: { type: 'round' }, legs: { count: 4, type: 'paw' }, tail: { type: 'scorpion', len: 0.7 }, extras: ['mane', 'whiskers'] },
  },

  // ─────────────── LEGENDARY ───────────────
  {
    id: 'nundu', name: 'Nundu', latin: 'Panthera pestifera', tier: 'legendary',
    blurb: 'A gigantic leopard that moves in silence; its breath carries disease enough to wipe out a village. The deadliest beast alive.',
    size: 1.8, speed: 1.4, roam: 9, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat', nocturnal: true,
    produces: { item: 'Nundu whisker', amount: 34, every: 140 }, unlockCost: 1400,
    care: { feed: 'Whole beasts', play: 'It takes a hundred wizards to subdue — and your trust to befriend', note: 'Steps without a sound.' },
    build: { archetype: 'beast', skin: 'fur', palette: { base: 0xb89a5a, belly: 0xe0cc94, accent: 0x6a5028, eye: 0xe0b030, spark: 0xa0d090, pattern: 'spots' },
      body: { len: 0.95, girth: 0.56 }, head: { shape: 'feline', size: 1.0 }, eyes: { count: 2, size: 0.15 }, ears: { type: 'round' }, legs: { count: 4, type: 'paw' }, tail: { type: 'tuft', len: 0.85 }, extras: ['whiskers', 'frill'] },
  },
  {
    id: 'basilisk', name: 'Basilisk', latin: 'Serpens rex', tier: 'legendary',
    blurb: 'The King of Serpents — a colossal green snake whose direct gaze brings instant death and whose venom is without rival.',
    size: 1.9, speed: 1.2, roam: 8, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat', nocturnal: true,
    produces: { item: 'Basilisk venom', amount: 40, every: 150 }, unlockCost: 1800,
    care: { feed: 'Spiders flee it; feed it meat', play: 'Approach with eyes averted', note: 'Hatched from a chicken\'s egg beneath a toad.' },
    build: { archetype: 'serpent', skin: 'scale', palette: { base: 0x2a6a2a, belly: 0x6aa84a, accent: 0x1a4a1a, horn: 0xd8c060, eye: 0xe0c030, spark: 0xa0e060 },
      body: { len: 1.3, girth: 0.42 }, head: { shape: 'draconic', size: 1.0 }, eyes: { count: 2, size: 0.16, glow: true }, legs: { count: 0, type: 'none' }, tail: { type: 'serpent', len: 1.0 }, extras: ['crest', 'spikes'] },
  },
  {
    id: 'horntail', name: 'Hungarian Horntail', latin: 'Draco horridus', tier: 'legendary',
    blurb: 'The most dangerous breed of dragon — black-scaled, bronze-horned, with a spiked tail and a forty-foot jet of flame.',
    size: 1.9, speed: 1.5, roam: 10, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat',
    produces: { item: 'dragon scale', amount: 44, every: 155 }, unlockCost: 2200,
    care: { feed: 'Whole cattle', play: 'Keep well clear of the flame', note: 'Yellow eyes, bronze horns, a tail of spikes.' },
    build: { archetype: 'dragon', skin: 'scale', palette: { base: 0x1e1e22, belly: 0x4a3a1a, accent: 0x2e2e34, horn: 0xb8923a, eye: 0xe0c030, spark: 0xff7030, wing: 0x18181c },
      body: { len: 1.0, girth: 0.6 }, head: { shape: 'draconic', size: 1.0 }, eyes: { count: 2, size: 0.14, glow: true }, horns: { type: 'pair', size: 0.34 }, wings: { type: 'bat', span: 1.6 }, legs: { count: 4, type: 'talon' }, tail: { type: 'scorpion', len: 1.0 }, extras: ['spikes', 'tusks'] },
  },

  // ─────────────── MYTHIC ───────────────
  {
    id: 'phoenix', name: 'Phoenix', latin: 'Avis renata', tier: 'mythic',
    blurb: 'A swan-sized scarlet bird with a golden tail, born again from its own ashes. Its tears heal; its song gives heart.',
    size: 1.2, speed: 1.7, roam: 10, diet: ['berries', 'honey_pot', 'gourmet_treat'], favorite: 'honey_pot',
    produces: { item: 'phoenix feather', amount: 50, every: 160 }, unlockCost: 3000,
    care: { feed: 'Sweet fruit & sunlight', play: 'Let its song lift your heart', note: 'Bursts to flame and rises from the ash.' },
    build: { archetype: 'avian', skin: 'feather', palette: { base: 0xd83a1a, belly: 0xf07030, accent: 0xf0c040, horn: 0xffd860, eye: 0x402000, spark: 0xffd040, wing: 0xe85a20 },
      body: { len: 0.7, girth: 0.36 }, head: { shape: 'beak', size: 0.85 }, eyes: { count: 2, size: 0.13, glow: true }, wings: { type: 'feather', span: 1.4 }, legs: { count: 2, type: 'talon' }, tail: { type: 'plume', len: 1.1 }, extras: ['crest', 'wisps'] },
  },
  {
    id: 'thunderbird', name: 'Thunderbird', latin: 'Avis tempestatis', tier: 'mythic',
    blurb: 'A great American bird with many wings that shimmer with cloud and sun; it senses danger and brews storms as it flies.',
    size: 1.6, speed: 1.8, roam: 11, diet: ['fresh_fish', 'raw_meat', 'gourmet_treat'], favorite: 'fresh_fish',
    produces: { item: 'thunderbird feather', amount: 52, every: 165 }, unlockCost: 3200,
    care: { feed: 'Fish from on high', play: 'Fly with it through the storm it makes', note: 'Each wing-beat rolls thunder.' },
    build: { archetype: 'avian', skin: 'feather', palette: { base: 0x8a6a3a, belly: 0xd8c088, accent: 0xf0e0b0, horn: 0xe0c060, eye: 0x402810, spark: 0xffe79a, wing: 0xa88a52 },
      body: { len: 0.85, girth: 0.42 }, head: { shape: 'beak', size: 0.9 }, eyes: { count: 2, size: 0.13, glow: true }, wings: { type: 'feather', span: 1.7 }, legs: { count: 2, type: 'talon' }, tail: { type: 'plume', len: 0.9 }, extras: ['crest'] },
  },
  {
    id: 'sphinx', name: 'Sphinx', latin: 'Sphinx aenigmatica', tier: 'mythic',
    blurb: 'A beast with the body of a great lion and the head of a woman, who guards treasures and speaks only in riddles.',
    size: 1.5, speed: 1.3, roam: 8, diet: ['raw_meat', 'honey_pot', 'gourmet_treat'], favorite: 'honey_pot',
    produces: { item: 'sphinx riddle', amount: 46, every: 150 }, unlockCost: 2800,
    care: { feed: 'Fine food & finer questions', play: 'Answer its riddle correctly', note: 'Violent only when its riddle is failed.' },
    build: { archetype: 'beast', skin: 'fur', palette: { base: 0xc8a45a, belly: 0xe0c890, accent: 0x8a6a30, horn: 0x4a3a1e, eye: 0x3a2a10, spark: 0xffe09a },
      body: { len: 0.9, girth: 0.52 }, head: { shape: 'round', size: 1.0 }, eyes: { count: 2, size: 0.15 }, ears: { type: 'round' }, legs: { count: 4, type: 'paw' }, tail: { type: 'tuft', len: 0.8 }, extras: ['mane'] },
  },
  {
    id: 'runespoor', name: 'Runespoor', latin: 'Serpens tricephalus', tier: 'mythic',
    blurb: 'A striking orange-and-black serpent with three heads — the Planner, the Dreamer and the Critic, forever bickering.',
    size: 1.3, speed: 1.3, roam: 8, diet: ['raw_meat', 'beetle', 'fresh_fish'], favorite: 'raw_meat', nocturnal: true,
    produces: { item: 'Runespoor egg', amount: 42, every: 145 }, unlockCost: 2600,
    care: { feed: 'Small mammals', play: 'Settle its three squabbling heads', note: 'Three heads rarely agree on anything.' },
    build: { archetype: 'serpent', skin: 'scale', palette: { base: 0xd86a20, belly: 0xf0a050, accent: 0x1a1a1a, horn: 0x2a2a2a, eye: 0xe0d020, spark: 0xffb060, pattern: 'stripes' },
      body: { len: 1.0, girth: 0.34 }, head: { shape: 'draconic', size: 0.85 }, eyes: { count: 2, size: 0.13, glow: true }, legs: { count: 0, type: 'none' }, tail: { type: 'serpent', len: 0.8 } },
  },

  // ═══════════ BATCH 2 ═══════════
  // ── COMMON ──
  {
    id: 'doxy', name: 'Doxy', latin: 'Doxus morsus', tier: 'common',
    blurb: 'A biting "dark fairy" covered in coarse black hair, with four arms, four legs and shiny beetle-like wings.',
    size: 0.45, speed: 2.1, roam: 10, diet: ['beetle', 'berries'], favorite: 'beetle',
    unlockCost: 35, care: { feed: 'Insects', play: 'Mind the venomous bite', note: 'Lays up to 500 eggs.' },
    build: { archetype: 'insectoid', skin: 'fur', palette: { base: 0x1a1a22, belly: 0x2e2e3a, accent: 0x4a4a6a, eye: 0x8a6ad0, spark: 0x6a4ab0, wing: 0x9a8ad0 },
      body: { len: 0.34, girth: 0.22 }, head: { shape: 'round', size: 0.9 }, eyes: { count: 2, size: 0.12 }, wings: { type: 'insect', span: 0.6 }, legs: { count: 6, type: 'stick' }, extras: ['antennae'] },
  },
  {
    id: 'fairy', name: 'Fairy', latin: 'Fata vulgaris', tier: 'common',
    blurb: 'A small, vain, human-shaped beast with gossamer insect wings — decorative and not very bright.',
    size: 0.4, speed: 1.9, roam: 9, diet: ['berries', 'honey_pot', 'sweet_truffle'], favorite: 'honey_pot',
    unlockCost: 45, care: { feed: 'Nectar', play: 'Let it preen and glitter', note: 'Loves to be admired.' },
    build: { archetype: 'humanoid', skin: 'smooth', palette: { base: 0xe8c8a0, belly: 0xf0d8b8, accent: 0x9ad8a0, eye: 0x3a6a40, spark: 0xbfffcf, wing: 0xcfffe0 },
      body: { len: 0.26, girth: 0.16 }, head: { shape: 'round', size: 1.0 }, eyes: { count: 2, size: 0.11 }, wings: { type: 'insect', span: 0.6 }, legs: { count: 2, type: 'stick' } },
  },
  {
    id: 'fire_crab', name: 'Fire Crab', latin: 'Cancer ignifer', tier: 'common',
    blurb: 'A jewelled tortoise-like beast whose gem-encrusted shell shoots flames from its rear when threatened.',
    size: 0.6, speed: 0.9, roam: 5, habitat: 'coast', diet: ['fresh_fish', 'beetle', 'leafy_greens'], favorite: 'fresh_fish',
    produces: { item: 'Fire Crab shell', amount: 12, every: 88 }, unlockCost: 90,
    care: { feed: 'Shellfish', play: 'Admire its jewelled back', note: 'Its shell is prized by thieves.' },
    build: { archetype: 'amphibian', skin: 'scale', palette: { base: 0xc85a2a, belly: 0xe8a050, accent: 0xffd040, horn: 0x8a3a1a, eye: 0x2a1208, spark: 0xff8030 },
      body: { len: 0.5, girth: 0.42 }, head: { shape: 'round', size: 0.7 }, eyes: { count: 2, size: 0.1 }, legs: { count: 4, type: 'webbed' }, tail: { type: 'none' }, extras: ['shell', 'gem'] },
  },
  {
    id: 'bundimun', name: 'Bundimun', latin: 'Fungus oculatus', tier: 'common',
    blurb: 'A creeping greenish fungus with countless eyes and spindly legs that rots the foundations of houses.',
    size: 0.5, speed: 0.8, roam: 4, diet: ['leafy_greens', 'beetle'], favorite: 'leafy_greens',
    produces: { item: 'Bundimun ooze', amount: 9, every: 80 }, unlockCost: 50,
    care: { feed: 'Grime', play: 'It oozes contentedly', note: 'Its secretion cleans, diluted.' },
    build: { archetype: 'amorphous', skin: 'slime', palette: { base: 0x5a7a3a, belly: 0x7a9a4a, accent: 0x9ac060, eye: 0x101810, spark: 0xaff060 },
      body: { len: 0.42, girth: 0.4 }, head: { shape: 'round', size: 0.6 }, eyes: { count: 6, size: 0.07 }, legs: { count: 6, type: 'stick' } },
  },
  {
    id: 'plimpy', name: 'Plimpy', latin: 'Piscis sphaericus', tier: 'common',
    blurb: 'A spherical, mottled lake-fish with two rubbery legs ending in webbed feet; merpeople tie its legs in knots.',
    size: 0.5, speed: 1.3, roam: 6, habitat: 'coast', diet: ['fresh_fish', 'beetle'], favorite: 'fresh_fish',
    unlockCost: 55, care: { feed: 'Water snails', play: 'Watch it bob', note: 'Harmless, if a nuisance.' },
    build: { archetype: 'aquatic', skin: 'smooth', palette: { base: 0x5a8a8a, belly: 0x8ac0c0, accent: 0xc8a040, eye: 0xe0c030, spark: 0xa0e0e0, pattern: 'spots' },
      body: { len: 0.4, girth: 0.42 }, head: { shape: 'frog', size: 0.8 }, eyes: { count: 2, size: 0.14 }, legs: { count: 2, type: 'webbed' }, tail: { type: 'fish', len: 0.4 } },
  },
  {
    id: 'streeler', name: 'Streeler', latin: 'Limax colormutans', tier: 'common',
    blurb: 'A giant snail that changes colour hour by hour and leaves a trail so venomous it scorches the earth.',
    size: 0.55, speed: 0.5, roam: 3, diet: ['leafy_greens', 'berries'], favorite: 'leafy_greens',
    produces: { item: 'Streeler shell', amount: 10, every: 84 }, unlockCost: 60,
    care: { feed: 'Leaves & nettles', play: 'Watch its colours shift', note: 'Its trail kills plants.' },
    build: { archetype: 'serpent', skin: 'slime', palette: { base: 0x9a5ad0, belly: 0xc090e0, accent: 0xe0d040, eye: 0x201030, spark: 0xd0a0ff },
      body: { len: 0.5, girth: 0.28 }, head: { shape: 'round', size: 0.7 }, eyes: { count: 2, size: 0.08 }, legs: { count: 0, type: 'none' }, tail: { type: 'serpent', len: 0.4 }, extras: ['shell', 'antennae'] },
  },

  // ── UNCOMMON ──
  {
    id: 'moke', name: 'Moke', latin: 'Lacerta minor', tier: 'uncommon',
    blurb: 'A silver-green lizard that can shrink at will to escape; its skin makes self-sizing wizard purses.',
    size: 0.5, speed: 1.6, roam: 8, diet: ['beetle', 'berries'], favorite: 'beetle',
    produces: { item: 'Moke skin', amount: 12, every: 84 }, unlockCost: 150,
    care: { feed: 'Insects', play: 'Catch it before it shrinks', note: 'It vanishes from danger by shrinking.' },
    build: { archetype: 'beast', skin: 'scale', palette: { base: 0x6a8a5a, belly: 0x9ac080, accent: 0x4a6a3a, eye: 0xc0a030, spark: 0xb0e090 },
      body: { len: 0.55, girth: 0.26 }, head: { shape: 'draconic', size: 0.7 }, eyes: { count: 2, size: 0.11 }, legs: { count: 4, type: 'stick' }, tail: { type: 'lizard', len: 0.7 } },
  },
  {
    id: 'grindylow', name: 'Grindylow', latin: 'Daemon aquaticus', tier: 'uncommon',
    blurb: 'A sickly-green water demon with sharp little horns and long, brittle fingers it uses to snare the unwary.',
    size: 0.55, speed: 1.5, roam: 7, habitat: 'coast', diet: ['fresh_fish', 'beetle'], favorite: 'fresh_fish', nocturnal: true,
    produces: { item: 'Grindylow horn', amount: 13, every: 86 }, unlockCost: 180,
    care: { feed: 'Small fish', play: 'Pry its grip loose gently', note: 'Strong, but its fingers snap easily.' },
    build: { archetype: 'aquatic', skin: 'smooth', palette: { base: 0x3a7a5a, belly: 0x5a9a78, accent: 0x2a5a44, horn: 0xc8d0b0, eye: 0xe0e060, spark: 0x80f0b0 },
      body: { len: 0.55, girth: 0.3 }, head: { shape: 'frog', size: 0.9 }, eyes: { count: 2, size: 0.15, glow: true }, horns: { type: 'pair', size: 0.16 }, legs: { count: 2, type: 'webbed' }, tail: { type: 'fish', len: 0.5 }, extras: ['frill'] },
  },
  {
    id: 'porlock', name: 'Porlock', latin: 'Custos equorum', tier: 'uncommon',
    blurb: 'A shy, shaggy horse-guardian covered in rough hair, with a large nose and four stubby cloven feet.',
    size: 0.7, speed: 1.3, roam: 8, habitat: 'forest', diet: ['leafy_greens', 'berries'], favorite: 'leafy_greens',
    produces: { item: 'Porlock hair', amount: 11, every: 82 }, unlockCost: 175,
    care: { feed: 'Grass & hay', play: 'It prefers horses to people', note: 'Hides in straw when watched.' },
    build: { archetype: 'beast', skin: 'fur', palette: { base: 0x6a5a3a, belly: 0x8a7a52, tip: 0x4a3e26, accent: 0x3a2e1a, eye: 0x1a1208, spark: 0xb0a070 },
      body: { len: 0.6, girth: 0.4 }, head: { shape: 'snout', size: 0.9 }, eyes: { count: 2, size: 0.1 }, ears: { type: 'round' }, legs: { count: 4, type: 'hoof' }, tail: { type: 'tuft', len: 0.4 }, extras: ['mane', 'beard'] },
  },
  {
    id: 'leprechaun', name: 'Leprechaun', latin: 'Homunculus aureus', tier: 'uncommon',
    blurb: 'A clever little green sprite that conjures gold which vanishes hours later. Fond of mischief.',
    size: 0.5, speed: 1.8, roam: 9, diet: ['gold_coin', 'berries', 'sweet_truffle'], favorite: 'gold_coin',
    produces: { item: 'leprechaun gold', amount: 16, every: 88 }, unlockCost: 220,
    care: { feed: 'Clover & gold', play: 'Chase the gold before it fades', note: 'Its gold disappears — caveat emptor.' },
    build: { archetype: 'humanoid', skin: 'smooth', palette: { base: 0x3a8a4a, belly: 0x5aaa64, accent: 0xe0c040, eye: 0x204020, spark: 0xffe060 },
      body: { len: 0.3, girth: 0.2 }, head: { shape: 'round', size: 1.1 }, eyes: { count: 2, size: 0.11 }, ears: { type: 'point' }, legs: { count: 2, type: 'paw' }, extras: ['beard'] },
  },
  {
    id: 'kelpie', name: 'Kelpie', latin: 'Equus aquaticus', tier: 'uncommon',
    blurb: 'A shape-shifting water demon most often a horse with a mane of bulrushes, luring riders to drown.',
    size: 1.1, speed: 1.7, roam: 9, habitat: 'coast', diet: ['fresh_fish', 'raw_meat'], favorite: 'fresh_fish', nocturnal: true,
    produces: { item: 'Kelpie reed', amount: 17, every: 95 }, unlockCost: 260,
    care: { feed: 'River fish', play: 'A bridle of will tames it', note: 'Its mane is woven of water-weed.' },
    build: { archetype: 'equine', skin: 'smooth', palette: { base: 0x2a3a4a, belly: 0x3e5260, accent: 0x4a6a3a, eye: 0x60d0a0, spark: 0x70c0e0 },
      body: { len: 0.7, girth: 0.4 }, head: { shape: 'equine', size: 0.9 }, eyes: { count: 2, size: 0.13, glow: true }, ears: { type: 'point' }, legs: { count: 4, type: 'hoof' }, tail: { type: 'plume', len: 0.7 }, extras: ['mane'] },
  },
  {
    id: 'hodag', name: 'Hodag', latin: 'Bufo cornutus', tier: 'uncommon',
    blurb: 'A horned, frog-eyed North American beast that drinks the blood of Mooncalves but bonds fiercely with wizards.',
    size: 0.8, speed: 1.4, roam: 8, diet: ['beetle', 'raw_meat', 'moon_pellet'], favorite: 'moon_pellet', nocturnal: true,
    produces: { item: 'Hodag horn', amount: 14, every: 90 }, unlockCost: 230,
    care: { feed: 'Insects & moon-pellets', play: 'It is loyal once won over', note: 'Lives near Mooncalf burrows.' },
    build: { archetype: 'amphibian', skin: 'hide', palette: { base: 0x5a5a4a, belly: 0x7a7a64, accent: 0x3a3a2e, horn: 0xc8c0a0, eye: 0xe0d040, spark: 0xa0d0a0 },
      body: { len: 0.6, girth: 0.42 }, head: { shape: 'frog', size: 1.0 }, eyes: { count: 2, size: 0.16 }, horns: { type: 'pair', size: 0.2 }, legs: { count: 4, type: 'webbed' }, tail: { type: 'lizard', len: 0.5 }, extras: ['spikes'] },
  },

  // ── RARE ──
  {
    id: 'kappa', name: 'Kappa', latin: 'Daemon fluvialis', tier: 'rare',
    blurb: 'A scaly, monkey-faced Japanese water demon with webbed hands and a water-filled hollow in its head.',
    size: 0.8, speed: 1.5, roam: 8, habitat: 'coast', diet: ['fresh_fish', 'leafy_greens'], favorite: 'leafy_greens', nocturnal: true,
    produces: { item: 'Kappa scale', amount: 18, every: 96 }, unlockCost: 380,
    care: { feed: 'Cucumbers (truly)', play: 'Bow — it must bow back and spill its water', note: 'Strength lives in its head-dish.' },
    build: { archetype: 'amphibian', skin: 'scale', palette: { base: 0x4a7a5a, belly: 0x7aaa80, accent: 0xc8a040, eye: 0x2a2010, spark: 0x90d0a0 },
      body: { len: 0.6, girth: 0.38 }, head: { shape: 'frog', size: 0.95 }, eyes: { count: 2, size: 0.13 }, legs: { count: 4, type: 'webbed' }, tail: { type: 'lizard', len: 0.4 }, extras: ['shell', 'frill'] },
  },
  {
    id: 'salamander', name: 'Salamander', latin: 'Lacerta ignis', tier: 'rare',
    blurb: 'A small fire-dwelling lizard, brilliant white turning red or blue with the heat of the flames it is born in.',
    size: 0.55, speed: 1.7, roam: 8, diet: ['beetle', 'raw_meat'], favorite: 'beetle',
    produces: { item: 'Salamander blood', amount: 19, every: 98 }, unlockCost: 400,
    care: { feed: 'Embers & insects', play: 'Keep its fire fed', note: 'Lives only as long as its flame burns.' },
    build: { archetype: 'beast', skin: 'scale', palette: { base: 0xe85030, belly: 0xffa060, accent: 0xffe040, horn: 0xffd060, eye: 0x301010, spark: 0xff7030 },
      body: { len: 0.5, girth: 0.24 }, head: { shape: 'draconic', size: 0.7 }, eyes: { count: 2, size: 0.12, glow: true }, legs: { count: 4, type: 'stick' }, tail: { type: 'lizard', len: 0.7 }, extras: ['wisps'] },
  },
  {
    id: 'ashwinder', name: 'Ashwinder', latin: 'Serpens cineris', tier: 'rare',
    blurb: 'A thin, pale-grey serpent with glowing red eyes, born from the embers of a magical fire left too long.',
    size: 0.7, speed: 1.8, roam: 9, diet: ['beetle', 'raw_meat'], favorite: 'beetle', nocturnal: true,
    produces: { item: 'Ashwinder egg', amount: 20, every: 100 }, unlockCost: 420,
    care: { feed: 'Warm-blooded prey', play: 'It lives only an hour unchecked — soothe it', note: 'Its red-hot eggs are used in Love Potions.' },
    build: { archetype: 'serpent', skin: 'smooth', palette: { base: 0x9a9aa0, belly: 0xc0c0c6, accent: 0x6a3030, eye: 0xff3020, spark: 0xff6040 },
      body: { len: 0.85, girth: 0.24 }, head: { shape: 'draconic', size: 0.7 }, eyes: { count: 2, size: 0.13, glow: true }, legs: { count: 0, type: 'none' }, tail: { type: 'serpent', len: 0.7 }, extras: ['wisps'] },
  },
  {
    id: 'tebo', name: 'Tebo', latin: 'Sus invisibilis', tier: 'rare',
    blurb: 'An ash-grey warthog of Congo and Zaire that can make itself invisible — much sought, hard to keep.',
    size: 0.9, speed: 1.5, roam: 8, diet: ['leafy_greens', 'beetle', 'raw_meat'], favorite: 'leafy_greens',
    produces: { item: 'Tebo tusk', amount: 18, every: 96 }, unlockCost: 410,
    care: { feed: 'Roots & grubs', play: 'Keep an eye out — it vanishes', note: 'Its hide is prized for camouflage.' },
    build: { archetype: 'beast', skin: 'hide', palette: { base: 0x7a7a72, belly: 0x9a9a90, accent: 0x4a4a44, horn: 0xd0c8b0, eye: 0x201810, spark: 0xb0b0a0 },
      body: { len: 0.7, girth: 0.46 }, head: { shape: 'snout', size: 0.9 }, eyes: { count: 2, size: 0.1 }, ears: { type: 'point' }, legs: { count: 4, type: 'hoof' }, tail: { type: 'tuft', len: 0.4 }, extras: ['tusks', 'wisps'] },
  },
  {
    id: 'glumbumble', name: 'Glumbumble', latin: 'Apis tristis', tier: 'rare',
    blurb: 'A fuzzy grey flying insect of northern Europe that produces a melancholy-inducing treacle.',
    size: 0.5, speed: 2.0, roam: 10, diet: ['honey_pot', 'berries', 'beetle'], favorite: 'honey_pot',
    produces: { item: 'Glumbumble treacle', amount: 17, every: 94 }, unlockCost: 360,
    care: { feed: 'Nettles', play: 'Its drone is oddly soothing', note: 'Its treacle counters Alihotsy hysteria.' },
    build: { archetype: 'insectoid', skin: 'fur', palette: { base: 0x6a6a72, belly: 0x9a9aa2, tip: 0x4a4a52, accent: 0xc8c0a0, eye: 0x101018, spark: 0xb0b0c0, wing: 0xd0d0e0 },
      body: { len: 0.4, girth: 0.28 }, head: { shape: 'round', size: 0.8 }, eyes: { count: 2, size: 0.11 }, wings: { type: 'insect', span: 0.7 }, legs: { count: 6, type: 'stick' }, extras: ['antennae'] },
  },
  {
    id: 'abraxan', name: 'Abraxan', latin: 'Equus alatus aureus', tier: 'rare',
    blurb: 'A giant, immensely powerful palomino winged horse that drinks only single-malt whisky. Madame Maxime\'s steeds.',
    size: 1.4, speed: 1.6, roam: 10, diet: ['leafy_greens', 'honey_pot', 'berries'], favorite: 'honey_pot',
    produces: { item: 'Abraxan hair', amount: 22, every: 108 }, unlockCost: 540,
    care: { feed: 'Fine grains', play: 'Fly with its golden wings', note: 'Enormous and strong-willed.' },
    build: { archetype: 'equine', skin: 'fur', palette: { base: 0xe0c878, belly: 0xf0e0a8, tip: 0xc8a850, accent: 0xfff0c0, eye: 0x3a2a10, spark: 0xfff0c0, wing: 0xf0e0b0 },
      body: { len: 0.8, girth: 0.45 }, head: { shape: 'equine', size: 0.95 }, eyes: { count: 2, size: 0.13 }, ears: { type: 'point' }, wings: { type: 'feather', span: 1.5 }, legs: { count: 4, type: 'hoof' }, tail: { type: 'plume', len: 0.8 }, extras: ['mane'] },
  },
  {
    id: 'snidget', name: 'Golden Snidget', latin: 'Avis aurata', tier: 'rare',
    blurb: 'A tiny, round, fully golden bird with red jewel-like eyes and rotating wings — the ancestor of the Golden Snitch.',
    size: 0.42, speed: 2.4, roam: 12, diet: ['berries', 'honey_pot', 'shiny_gem'], favorite: 'shiny_gem',
    produces: { item: 'Snidget feather', amount: 24, every: 100 }, unlockCost: 480,
    care: { feed: 'Berries & nectar', play: 'Catch it if you can — it darts', note: 'Protected; once hunted in Quidditch.' },
    build: { archetype: 'avian', skin: 'feather', palette: { base: 0xe8c040, belly: 0xf0d870, accent: 0xfff0a0, horn: 0xffe060, eye: 0xd03020, spark: 0xffe79a, wing: 0xf0d060 },
      body: { len: 0.32, girth: 0.3 }, head: { shape: 'beak', size: 0.8 }, eyes: { count: 2, size: 0.12, glow: true }, wings: { type: 'feather', span: 0.7 }, legs: { count: 2, type: 'talon' }, tail: { type: 'plume', len: 0.4 } },
  },

  // ── ULTRA RARE ──
  {
    id: 'chimaera', name: 'Chimaera', latin: 'Chimaera tricorpus', tier: 'ultra',
    blurb: 'A rare and vicious Greek beast with a lion\'s head, a goat\'s body and a dragon\'s tail. Bloodthirsty.',
    size: 1.5, speed: 1.6, roam: 9, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat', nocturnal: true,
    produces: { item: 'Chimaera scale', amount: 30, every: 130 }, unlockCost: 880,
    care: { feed: 'Plentiful meat', play: 'Only one wizard is known to have tamed one', note: 'Three natures, one ferocious whole.' },
    build: { archetype: 'beast', skin: 'fur', palette: { base: 0xb8843a, belly: 0xd8aa60, accent: 0x6a4a2a, horn: 0xc8c0a0, eye: 0xe0a030, spark: 0xc8504a },
      body: { len: 0.85, girth: 0.5, hump: true }, head: { shape: 'feline', size: 1.0 }, eyes: { count: 2, size: 0.14 }, ears: { type: 'round' }, horns: { type: 'pair', size: 0.24 }, legs: { count: 4, type: 'hoof' }, tail: { type: 'serpent', len: 0.8 }, extras: ['mane', 'spikes'] },
  },
  {
    id: 'quintaped', name: 'Quintaped', latin: 'Quinque pedis', tier: 'ultra',
    blurb: 'A horror of the Isle of Drear: a squat, reddish-brown body thick with hair, on five clubbed feet. A man-eater.',
    size: 1.1, speed: 1.7, roam: 8, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat', nocturnal: true,
    produces: { item: 'Quintaped hair', amount: 28, every: 125 }, unlockCost: 760,
    care: { feed: 'Meat — it prefers humans', play: 'Keep your distance until trust forms', note: 'Endemic to one hidden island.' },
    build: { archetype: 'arachnid', skin: 'fur', palette: { base: 0x7a3a2a, belly: 0x9a5a3a, tip: 0x5a2818, accent: 0x3a1e14, eye: 0x100806, spark: 0xb05030 },
      body: { len: 0.5, girth: 0.42 }, head: { shape: 'round', size: 0.6 }, eyes: { count: 4, size: 0.07 }, legs: { count: 6, type: 'paw' }, extras: ['mane'] },
  },
  {
    id: 'wampus', name: 'Wampus Cat', latin: 'Felis sexpes', tier: 'ultra',
    blurb: 'A six-legged, cougar-like beast of Appalachia, fast as lightning, with hypnotic yellow eyes and great strength.',
    size: 1.3, speed: 2.0, roam: 10, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat', nocturnal: true,
    produces: { item: 'Wampus hair', amount: 29, every: 128 }, unlockCost: 840,
    care: { feed: 'Fresh game', play: 'Avoid its hypnotic stare', note: 'Its hair is a powerful wand core.' },
    build: { archetype: 'beast', skin: 'fur', palette: { base: 0x8a6a4a, belly: 0xc8a878, accent: 0x5a4028, eye: 0xf0d030, spark: 0xb0d090 },
      body: { len: 0.9, girth: 0.5 }, head: { shape: 'feline', size: 0.95 }, eyes: { count: 2, size: 0.15, glow: true }, ears: { type: 'tuft' }, legs: { count: 6, type: 'paw' }, tail: { type: 'tuft', len: 0.85 }, extras: ['whiskers'] },
  },
  {
    id: 'yeti', name: 'Yeti', latin: 'Homo niveus', tier: 'ultra',
    blurb: 'A towering Tibetan beast of shaggy white fur, up to fifteen feet tall, that devours anything in its path.',
    size: 1.7, speed: 1.2, roam: 8, habitat: 'mountain', diet: ['raw_meat', 'fresh_fish', 'leafy_greens'], favorite: 'raw_meat',
    produces: { item: 'Yeti fur', amount: 27, every: 124 }, unlockCost: 780,
    care: { feed: 'Whatever it can reach', play: 'Fire is the only thing it fears', note: 'Also called the Abominable Snowman.' },
    build: { archetype: 'humanoid', skin: 'fur', palette: { base: 0xe0e4ea, belly: 0xf0f2f6, tip: 0xc0c8d0, accent: 0xa8b0bc, eye: 0x202028, spark: 0xeaf0ff },
      body: { len: 0.6, girth: 0.5 }, head: { shape: 'round', size: 1.0 }, eyes: { count: 2, size: 0.13 }, legs: { count: 2, type: 'paw' }, extras: ['mane', 'tusks'] },
  },
  {
    id: 'acromantula', name: 'Acromantula', latin: 'Aranea gigantea', tier: 'ultra',
    blurb: 'A monstrous, sentient spider with a body that can span fifteen feet, eight black eyes, and pincers that click as it talks.',
    size: 1.6, speed: 1.7, roam: 9, habitat: 'forest', diet: ['raw_meat', 'fresh_fish', 'beetle'], favorite: 'raw_meat', nocturnal: true,
    produces: { item: 'Acromantula silk', amount: 32, every: 135 }, unlockCost: 900,
    care: { feed: 'Large prey', play: 'Speak softly to it', note: 'Capable of human speech; native to Borneo.' },
    build: { archetype: 'arachnid', skin: 'fur', palette: { base: 0x1a1a1e, belly: 0x2e2e34, tip: 0x0e0e12, accent: 0x4a4a30, eye: 0x101010, spark: 0x6a6a4a },
      body: { len: 0.7, girth: 0.5 }, head: { shape: 'round', size: 0.7 }, eyes: { count: 8, size: 0.06 }, legs: { count: 8, type: 'stick' }, extras: ['tusks'] },
  },

  // ── LEGENDARY ──
  {
    id: 'lethifold', name: 'Lethifold', latin: 'Pallium mortis', tier: 'legendary',
    blurb: 'A living black shroud, no thicker than a cloak, that glides across the ground at night and smothers the sleeping.',
    size: 1.2, speed: 1.4, roam: 9, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat', nocturnal: true,
    produces: { item: 'Lethifold essence', amount: 38, every: 148 }, unlockCost: 1500,
    care: { feed: 'It consumes whole', play: 'Only a Patronus repels it — earn its calm instead', note: 'Leaves no trace of its prey.' },
    build: { archetype: 'amorphous', skin: 'ethereal', palette: { base: 0x0a0a10, belly: 0x14141c, accent: 0x2a2a3a, eye: 0x6a6a8a, spark: 0x4a4a6a },
      body: { len: 0.7, girth: 0.5 }, head: { shape: 'round', size: 0.7 }, eyes: { count: 2, size: 0.12, glow: true }, legs: { count: 0, type: 'none' }, extras: ['wisps'] },
  },
  {
    id: 'welsh_green', name: 'Common Welsh Green', latin: 'Draco viridis', tier: 'legendary',
    blurb: 'A grass-green dragon that blends into the Welsh hills; melodious of roar and, by dragon standards, mild.',
    size: 1.8, speed: 1.4, roam: 10, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat',
    produces: { item: 'dragon scale (green)', amount: 42, every: 152 }, unlockCost: 1900,
    care: { feed: 'Sheep, mostly', play: 'A surprisingly tuneful roar', note: 'Prefers to hunt sheep, shuns humans.' },
    build: { archetype: 'dragon', skin: 'scale', palette: { base: 0x3a7a32, belly: 0x6aa84a, accent: 0x2a5a22, horn: 0xc8c090, eye: 0xe0c030, spark: 0xff8030, wing: 0x2e6a28 },
      body: { len: 0.95, girth: 0.56 }, head: { shape: 'draconic', size: 0.95 }, eyes: { count: 2, size: 0.13, glow: true }, horns: { type: 'pair', size: 0.3 }, wings: { type: 'bat', span: 1.5 }, legs: { count: 4, type: 'talon' }, tail: { type: 'lizard', len: 0.95 }, extras: ['spikes'] },
  },
  {
    id: 'chinese_fireball', name: 'Chinese Fireball', latin: 'Draco igniglobus', tier: 'legendary',
    blurb: 'A scarlet, snub-snouted dragon fringed with golden spikes, that shoots its flame in mushroom-shaped balls of fire.',
    size: 1.85, speed: 1.5, roam: 10, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat',
    produces: { item: 'dragon scale (scarlet)', amount: 44, every: 154 }, unlockCost: 2050,
    care: { feed: 'Pigs and humans (beware)', play: 'Its fireballs bloom like mushrooms', note: 'Golden-fringed eyes; very aggressive.' },
    build: { archetype: 'dragon', skin: 'scale', palette: { base: 0xc8281a, belly: 0xe85a30, accent: 0xffc040, horn: 0xffd860, eye: 0xffe040, spark: 0xff5020, wing: 0xa81e14 },
      body: { len: 0.95, girth: 0.58 }, head: { shape: 'draconic', size: 0.95 }, eyes: { count: 2, size: 0.14, glow: true }, horns: { type: 'pair', size: 0.28 }, wings: { type: 'bat', span: 1.55 }, legs: { count: 4, type: 'talon' }, tail: { type: 'lizard', len: 0.9 }, extras: ['spikes', 'crest'] },
  },
  {
    id: 'norwegian_ridgeback', name: 'Norwegian Ridgeback', latin: 'Draco dorsospinus', tier: 'legendary',
    blurb: 'A black dragon with bronze ridged spines down its back and unusually venomous fangs. Norbert was one such.',
    size: 1.85, speed: 1.5, roam: 10, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat',
    produces: { item: 'dragon scale (black)', amount: 43, every: 153 }, unlockCost: 1980,
    care: { feed: 'Large mammals & water-beasts', play: 'Note the jet-black ridged spine', note: 'Breathes fire earlier than most.' },
    build: { archetype: 'dragon', skin: 'scale', palette: { base: 0x24242a, belly: 0x4a3a1a, accent: 0xb8923a, horn: 0xb8923a, eye: 0xc0d030, spark: 0xff7030, wing: 0x1c1c22 },
      body: { len: 0.95, girth: 0.56 }, head: { shape: 'draconic', size: 0.95 }, eyes: { count: 2, size: 0.13, glow: true }, horns: { type: 'pair', size: 0.3 }, wings: { type: 'bat', span: 1.5 }, legs: { count: 4, type: 'talon' }, tail: { type: 'lizard', len: 0.95 }, extras: ['spikes'] },
  },
  {
    id: 'ironbelly', name: 'Ukrainian Ironbelly', latin: 'Draco maximus', tier: 'legendary',
    blurb: 'The largest dragon breed of all — metallic grey, with talons long as scythes and eyes of deep red. One sank a sailing ship.',
    size: 1.95, speed: 1.2, roam: 11, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat',
    produces: { item: 'dragon scale (iron)', amount: 48, every: 158 }, unlockCost: 2400,
    care: { feed: 'Cattle by the herd', play: 'Sheer size demands respect', note: 'Can top six tonnes.' },
    build: { archetype: 'dragon', skin: 'scale', palette: { base: 0x6a6e76, belly: 0x8a8e96, accent: 0x4a4e56, horn: 0xc0c4cc, eye: 0xd03020, spark: 0xff8040, wing: 0x5a5e66 },
      body: { len: 1.05, girth: 0.64 }, head: { shape: 'draconic', size: 1.0 }, eyes: { count: 2, size: 0.14, glow: true }, horns: { type: 'pair', size: 0.34 }, wings: { type: 'bat', span: 1.7 }, legs: { count: 4, type: 'talon' }, tail: { type: 'scorpion', len: 1.0 }, extras: ['spikes', 'tusks'] },
  },

  // ── MYTHIC ──
  {
    id: 'opaleye', name: 'Antipodean Opaleye', latin: 'Draco opalinus', tier: 'mythic',
    blurb: 'A breathtaking dragon of pearly, iridescent scales and glittering, pupil-less opal eyes; it breathes scarlet flame.',
    size: 1.8, speed: 1.5, roam: 11, diet: ['raw_meat', 'fresh_fish', 'gourmet_treat'], favorite: 'fresh_fish',
    produces: { item: 'opal dragon scale', amount: 50, every: 160 }, unlockCost: 3100,
    care: { feed: 'Sheep — it rarely kills more than needed', play: 'Marvel at its shifting opal sheen', note: 'The least aggressive of dragons.' },
    build: { archetype: 'dragon', skin: 'scale', palette: { base: 0xc8d0e0, belly: 0xe8e0f0, accent: 0xc0a0e0, horn: 0xfff0d0, eye: 0xf0f0ff, spark: 0xffd0e0, wing: 0xb8c0d8 },
      body: { len: 0.95, girth: 0.56 }, head: { shape: 'draconic', size: 0.95 }, eyes: { count: 2, size: 0.14, glow: true }, horns: { type: 'pair', size: 0.28 }, wings: { type: 'bat', span: 1.6 }, legs: { count: 4, type: 'talon' }, tail: { type: 'lizard', len: 0.95 }, extras: ['spikes', 'crest'] },
  },
  {
    id: 'sea_serpent', name: 'Sea Serpent', latin: 'Serpens marinus', tier: 'mythic',
    blurb: 'A vast horse-headed serpent of the deep oceans, its humped green body rearing in coils from the waves.',
    size: 1.8, speed: 1.3, roam: 10, habitat: 'coast', diet: ['fresh_fish', 'raw_meat'], favorite: 'fresh_fish', nocturnal: true,
    produces: { item: 'sea-serpent scale', amount: 46, every: 156 }, unlockCost: 2900,
    care: { feed: 'Whole shoals of fish', play: 'Watch its great coils ripple', note: 'Frightening to behold, rarely harmful.' },
    build: { archetype: 'serpent', skin: 'scale', palette: { base: 0x2a6a6a, belly: 0x4a9a8a, accent: 0x1a4a4a, horn: 0xc8d0b0, eye: 0xe0c030, spark: 0x80e0d0 },
      body: { len: 1.4, girth: 0.4 }, head: { shape: 'equine', size: 1.0 }, eyes: { count: 2, size: 0.14 }, legs: { count: 0, type: 'none' }, tail: { type: 'serpent', len: 1.1 }, extras: ['mane', 'crest'] },
  },
  {
    id: 'vipertooth', name: 'Peruvian Vipertooth', latin: 'Draco venenatus', tier: 'mythic',
    blurb: 'The smallest, swiftest dragon — smooth copper scales, short black ridge-horns and venomous fangs that crave human flesh.',
    size: 1.5, speed: 1.9, roam: 11, diet: ['raw_meat', 'fresh_fish', 'gourmet_treat'], favorite: 'raw_meat',
    produces: { item: 'vipertooth fang', amount: 47, every: 156 }, unlockCost: 2950,
    care: { feed: 'Goats and birds', play: 'Quick and venomous — stay sharp', note: 'So bloodthirsty its numbers are culled.' },
    build: { archetype: 'dragon', skin: 'scale', palette: { base: 0xb8702a, belly: 0xd89850, accent: 0x2a2a2a, horn: 0x1a1a1a, eye: 0xe0d020, spark: 0xff9040, wing: 0xa8601e },
      body: { len: 0.85, girth: 0.48 }, head: { shape: 'draconic', size: 0.9 }, eyes: { count: 2, size: 0.13, glow: true }, horns: { type: 'pair', size: 0.22 }, wings: { type: 'bat', span: 1.4 }, legs: { count: 4, type: 'talon' }, tail: { type: 'lizard', len: 0.9 }, extras: ['spikes'] },
  },
  {
    id: 'hebridean_black', name: 'Hebridean Black', latin: 'Draco ater', tier: 'mythic',
    blurb: 'Britain\'s other native dragon — rough dark scales, brilliant purple eyes, a ridge of low spikes and an arrow-tipped tail.',
    size: 1.85, speed: 1.5, roam: 10, diet: ['raw_meat', 'fresh_fish', 'gourmet_treat'], favorite: 'raw_meat',
    produces: { item: 'hebridean scale', amount: 48, every: 158 }, unlockCost: 3050,
    care: { feed: 'Deer and large prey', play: 'Note the violet eyes and arrow tail', note: 'A clan once kept a tame one.' },
    build: { archetype: 'dragon', skin: 'scale', palette: { base: 0x22222e, belly: 0x33334a, accent: 0x5a4a6a, horn: 0x8a8a9a, eye: 0xa040e0, spark: 0xb060ff, wing: 0x1a1a26 },
      body: { len: 0.98, girth: 0.58 }, head: { shape: 'draconic', size: 0.98 }, eyes: { count: 2, size: 0.14, glow: true }, horns: { type: 'pair', size: 0.3 }, wings: { type: 'bat', span: 1.6 }, legs: { count: 4, type: 'talon' }, tail: { type: 'scorpion', len: 1.0 }, extras: ['spikes', 'crest'] },
  },

  // ═══════════ BATCH 3 ═══════════
  // ── COMMON ──
  {
    id: 'cornish_pixie', name: 'Cornish Pixie', latin: 'Pixum electricum', tier: 'common',
    blurb: 'An electric-blue, shrill little troublemaker that flies, pinches, and delights in chaos.',
    size: 0.42, speed: 2.3, roam: 11, diet: ['berries', 'sweet_truffle', 'beetle'], favorite: 'sweet_truffle',
    unlockCost: 45, care: { feed: 'Sweets', play: 'Good luck catching it', note: 'Freezing Charm recommended.' },
    build: { archetype: 'humanoid', skin: 'smooth', palette: { base: 0x2a6ad0, belly: 0x5a9af0, accent: 0x8ac0ff, eye: 0x101040, spark: 0x9ac8ff, wing: 0xcfe8ff },
      body: { len: 0.26, girth: 0.16 }, head: { shape: 'round', size: 1.0 }, eyes: { count: 2, size: 0.12 }, ears: { type: 'point' }, wings: { type: 'insect', span: 0.55 }, legs: { count: 2, type: 'stick' } },
  },
  {
    id: 'imp', name: 'Imp', latin: 'Imp vulgaris', tier: 'common',
    blurb: 'A small, dingy-brown prankster of British bogs, much like a pixie but flightless and even ruder.',
    size: 0.45, speed: 1.7, roam: 9, diet: ['beetle', 'berries'], favorite: 'beetle',
    unlockCost: 30, care: { feed: 'Insects', play: 'It loves to trip you', note: 'Crude sense of humour.' },
    build: { archetype: 'humanoid', skin: 'hide', palette: { base: 0x6a4a32, belly: 0x8a6a4a, accent: 0x4a3220, eye: 0x201408, spark: 0xc0a070 },
      body: { len: 0.28, girth: 0.18 }, head: { shape: 'round', size: 1.0 }, eyes: { count: 2, size: 0.11 }, ears: { type: 'point' }, legs: { count: 2, type: 'paw' } },
  },
  {
    id: 'nogtail', name: 'Nogtail', latin: 'Porcus daemonis', tier: 'common',
    blurb: 'A demonic, stunted piglet with spindly legs and a stubby tail that suckles among farm pigs to blight the land.',
    size: 0.55, speed: 1.6, roam: 8, diet: ['leafy_greens', 'beetle', 'raw_meat'], favorite: 'leafy_greens',
    unlockCost: 40, care: { feed: 'Slops', play: 'Only a pure-white dog can chase it off', note: 'Brings bad luck to a farm.' },
    build: { archetype: 'beast', skin: 'smooth', palette: { base: 0xc8a890, belly: 0xe0c4ac, accent: 0x9a7a62, eye: 0x201410, spark: 0xd8b8a0 },
      body: { len: 0.55, girth: 0.36 }, head: { shape: 'snout', size: 0.9 }, eyes: { count: 2, size: 0.1 }, ears: { type: 'point' }, legs: { count: 4, type: 'stick' }, tail: { type: 'tuft', len: 0.3 } },
  },
  {
    id: 'ghoul', name: 'Ghoul', latin: 'Larva domestica', tier: 'common',
    blurb: 'A slimy, buck-toothed ogre-ish creature that haunts attics and barns, harmless but for the odd moan.',
    size: 0.8, speed: 1.0, roam: 6, diet: ['beetle', 'raw_meat'], favorite: 'raw_meat', nocturnal: true,
    unlockCost: 50, care: { feed: 'Spiders & moths', play: 'It mostly groans', note: 'Quite content in a dusty attic.' },
    build: { archetype: 'humanoid', skin: 'slime', palette: { base: 0x7a7a6a, belly: 0x9a9a86, accent: 0x5a5a4a, eye: 0xc8c040, spark: 0xa0a080 },
      body: { len: 0.45, girth: 0.34 }, head: { shape: 'round', size: 1.1 }, eyes: { count: 2, size: 0.13 }, legs: { count: 2, type: 'paw' }, extras: ['tusks'] },
  },
  {
    id: 'redcap', name: 'Red Cap', latin: 'Nanus cruentus', tier: 'common',
    blurb: 'A squat, dwarf-like goblin that lurks where blood has been spilt, its cap dyed crimson, ready to club the unwary.',
    size: 0.55, speed: 1.6, roam: 8, diet: ['raw_meat', 'beetle'], favorite: 'raw_meat', nocturnal: true,
    unlockCost: 55, care: { feed: 'Raw scraps', play: 'Keep to well-lit places', note: 'Drawn to old battlefields.' },
    build: { archetype: 'humanoid', skin: 'hide', palette: { base: 0x6a5a4a, belly: 0x8a7a64, accent: 0xc02828, eye: 0x201810, spark: 0xe04040 },
      body: { len: 0.3, girth: 0.22 }, head: { shape: 'round', size: 1.1 }, eyes: { count: 2, size: 0.11 }, ears: { type: 'point' }, legs: { count: 2, type: 'paw' }, extras: ['crest', 'beard'] },
  },
  {
    id: 'hinkypunk', name: 'Hinkypunk', latin: 'Lumen errans', tier: 'common',
    blurb: 'A frail, one-legged wisp of smoke that carries a pale lantern to lure travellers off their path into the mire.',
    size: 0.6, speed: 1.4, roam: 8, habitat: 'coast', diet: ['beetle', 'berries'], favorite: 'beetle', nocturnal: true,
    unlockCost: 60, care: { feed: 'Marsh-light & midges', play: 'Follow its lantern (carefully)', note: 'It means to lead you astray.' },
    build: { archetype: 'amorphous', skin: 'ethereal', palette: { base: 0x4a5a6a, belly: 0x6a7a8a, accent: 0xc8e0a0, eye: 0xd0f060, spark: 0xc8f0a0 },
      body: { len: 0.4, girth: 0.3 }, head: { shape: 'round', size: 0.8 }, eyes: { count: 2, size: 0.12, glow: true }, legs: { count: 1, type: 'stick' }, extras: ['gem', 'wisps'] },
  },
  {
    id: 'dugbog', name: 'Dugbog', latin: 'Lignum vorans', tier: 'common',
    blurb: 'A marsh-dweller that looks like a piece of dead wood until it lunges on clawed feet to seize the unwary.',
    size: 0.7, speed: 1.3, roam: 7, habitat: 'coast', diet: ['beetle', 'fresh_fish', 'leafy_greens'], favorite: 'fresh_fish',
    unlockCost: 45, care: { feed: 'Mandrakes & frogs', play: 'Spot it before it moves', note: 'Disguised as a floating log.' },
    build: { archetype: 'amphibian', skin: 'bark', palette: { base: 0x4a4030, belly: 0x6a5a40, accent: 0x2e2818, eye: 0xc8a020, spark: 0x8a7a50 },
      body: { len: 0.7, girth: 0.32 }, head: { shape: 'frog', size: 0.9 }, eyes: { count: 2, size: 0.1 }, legs: { count: 4, type: 'webbed' }, tail: { type: 'lizard', len: 0.4 }, extras: ['spikes'] },
  },

  // ── UNCOMMON ──
  {
    id: 'malaclaw', name: 'Mackled Malaclaw', latin: 'Astacus terrestris', tier: 'uncommon',
    blurb: 'A spiny, greyish-green land "lobster" of rocky coasts whose bite curses the victim with a week of bad luck.',
    size: 0.6, speed: 1.4, roam: 7, habitat: 'coast', diet: ['fresh_fish', 'beetle'], favorite: 'fresh_fish',
    produces: { item: 'Malaclaw shell', amount: 12, every: 84 }, unlockCost: 160,
    care: { feed: 'Shellfish', play: 'Avoid the pincers', note: 'A bite ruins your luck for a week.' },
    build: { archetype: 'arachnid', skin: 'chitin', palette: { base: 0x6a7a5a, belly: 0x8a9a72, accent: 0x4a5a3a, eye: 0x201810, spark: 0x9ab080 },
      body: { len: 0.5, girth: 0.34 }, head: { shape: 'round', size: 0.7 }, eyes: { count: 4, size: 0.06 }, legs: { count: 6, type: 'stick' }, tail: { type: 'lizard', len: 0.4 }, extras: ['spikes', 'tusks'] },
  },
  {
    id: 'ramora', name: 'Ramora', latin: 'Piscis argenteus', tier: 'uncommon',
    blurb: 'A silver Indian Ocean fish of powerful magic that can anchor ships fast and guards seafarers from harm.',
    size: 0.6, speed: 1.6, roam: 8, habitat: 'coast', diet: ['fresh_fish', 'beetle'], favorite: 'fresh_fish',
    produces: { item: 'Ramora scale', amount: 13, every: 86 }, unlockCost: 170,
    care: { feed: 'Plankton & krill', play: 'Let it glide', note: 'Protected by the International Confederation.' },
    build: { archetype: 'aquatic', skin: 'scale', palette: { base: 0xb8c0cc, belly: 0xe0e6ee, accent: 0x8a9aa8, eye: 0x202830, spark: 0xcfe0f0 },
      body: { len: 0.7, girth: 0.3 }, head: { shape: 'round', size: 0.8 }, eyes: { count: 2, size: 0.12 }, legs: { count: 0, type: 'none' }, tail: { type: 'fish', len: 0.6 }, extras: ['frill'] },
  },
  {
    id: 'shrake', name: 'Shrake', latin: 'Piscis spinosus', tier: 'uncommon',
    blurb: 'An Atlantic fish entirely covered in spines, that tangles and tears the nets of any who anger merfolk.',
    size: 0.6, speed: 1.5, roam: 8, habitat: 'coast', diet: ['fresh_fish', 'beetle'], favorite: 'fresh_fish',
    produces: { item: 'Shrake spine', amount: 12, every: 84 }, unlockCost: 155,
    care: { feed: 'Smaller fish', play: 'Mind the spines', note: 'First bred to spite rude fishermen.' },
    build: { archetype: 'aquatic', skin: 'scale', palette: { base: 0x3a4a5a, belly: 0x5a6a7a, accent: 0x8a9aaa, horn: 0xc8d0d8, eye: 0xc0c040, spark: 0x90a0b0 },
      body: { len: 0.65, girth: 0.3 }, head: { shape: 'round', size: 0.8 }, eyes: { count: 2, size: 0.1 }, legs: { count: 0, type: 'none' }, tail: { type: 'fish', len: 0.6 }, extras: ['spikes'] },
  },
  {
    id: 'pogrebin', name: 'Pogrebin', latin: 'Daemon saxeus', tier: 'uncommon',
    blurb: 'A small Russian demon, a hairy grey body topped by a smooth rock-like head, that trails people to sap their will.',
    size: 0.5, speed: 1.5, roam: 8, diet: ['beetle', 'raw_meat'], favorite: 'beetle', nocturnal: true,
    produces: { item: 'Pogrebin stone', amount: 11, every: 82 }, unlockCost: 150,
    care: { feed: 'Grubs', play: 'Shake off the gloom it brings', note: 'Curls into a "rock" when noticed.' },
    build: { archetype: 'humanoid', skin: 'fur', palette: { base: 0x5a5a52, belly: 0x7a7a70, tip: 0x3a3a34, accent: 0x8a8a82, eye: 0x100c08, spark: 0xa0a098 },
      body: { len: 0.3, girth: 0.26 }, head: { shape: 'round', size: 1.0 }, eyes: { count: 2, size: 0.09 }, legs: { count: 2, type: 'paw' }, extras: ['mane'] },
  },
  {
    id: 'hidebehind', name: 'Hidebehind', latin: 'Umbra noctis', tier: 'uncommon',
    blurb: 'A nocturnal North American beast that can flatten and vanish behind the slimmest trunk; rarely glimpsed, never twice.',
    size: 0.9, speed: 1.5, roam: 8, habitat: 'forest', diet: ['raw_meat', 'beetle'], favorite: 'raw_meat', nocturnal: true,
    produces: { item: 'Hidebehind hair', amount: 14, every: 90 }, unlockCost: 210,
    care: { feed: 'Small game', play: 'You will never quite see it whole', note: 'Always just behind something.' },
    build: { archetype: 'humanoid', skin: 'ethereal', palette: { base: 0x1a1e24, belly: 0x2a2e36, accent: 0x4a4e58, eye: 0xc0c8d0, spark: 0x6a7080 },
      body: { len: 0.55, girth: 0.28 }, head: { shape: 'round', size: 0.9 }, eyes: { count: 2, size: 0.13, glow: true }, legs: { count: 2, type: 'stick' }, extras: ['wisps', 'mane'] },
  },
  {
    id: 'matagot', name: 'Matagot', latin: 'Felis spiritus', tier: 'uncommon',
    blurb: 'A spirit-beast that takes the shape of a scrawny black cat to guard old French wizarding places; only multiplies when struck.',
    size: 0.6, speed: 1.8, roam: 9, diet: ['fresh_fish', 'raw_meat', 'beetle'], favorite: 'fresh_fish', nocturnal: true,
    produces: { item: 'Matagot whisker', amount: 13, every: 86 }, unlockCost: 200,
    care: { feed: 'Fish & calm', play: 'Never strike it — it splits', note: 'Harmless unless provoked.' },
    build: { archetype: 'beast', skin: 'fur', palette: { base: 0x15151c, belly: 0x26262e, tip: 0x0c0c12, accent: 0x3a3a44, eye: 0xc8d030, spark: 0x6a6a8a },
      body: { len: 0.58, girth: 0.3 }, head: { shape: 'feline', size: 0.85 }, eyes: { count: 2, size: 0.14, glow: true }, ears: { type: 'point' }, legs: { count: 4, type: 'paw' }, tail: { type: 'tuft', len: 0.7 }, extras: ['whiskers', 'wisps'] },
  },

  // ── RARE ──
  {
    id: 'hippocampus', name: 'Hippocampus', latin: 'Equus marinus', tier: 'rare',
    blurb: 'A graceful sea-beast with the head and forequarters of a horse and the iridescent tail of a great fish.',
    size: 1.1, speed: 1.6, roam: 9, habitat: 'coast', diet: ['fresh_fish', 'leafy_greens'], favorite: 'fresh_fish',
    produces: { item: 'Hippocampus hair', amount: 18, every: 96 }, unlockCost: 400,
    care: { feed: 'Seaweed & shrimp', play: 'Swim alongside it', note: 'Lays large, semi-transparent eggs.' },
    build: { archetype: 'aquatic', skin: 'scale', palette: { base: 0x3a8a8a, belly: 0x6abaaa, accent: 0x88e0c0, eye: 0x203030, spark: 0x90f0d0 },
      body: { len: 0.7, girth: 0.36 }, head: { shape: 'equine', size: 0.9 }, eyes: { count: 2, size: 0.13 }, ears: { type: 'point' }, legs: { count: 0, type: 'none' }, tail: { type: 'fish', len: 0.8 }, extras: ['mane'] },
  },
  {
    id: 'aethonan', name: 'Aethonan', latin: 'Equus alatus castaneus', tier: 'rare',
    blurb: 'A chestnut winged horse, popular in Britain and Ireland — proud, strong, and devoted to a chosen rider.',
    size: 1.4, speed: 1.7, roam: 10, diet: ['leafy_greens', 'berries', 'honey_pot'], favorite: 'leafy_greens',
    produces: { item: 'Aethonan hair', amount: 21, every: 106 }, unlockCost: 520,
    care: { feed: 'Grains & apples', play: 'Earn the right to fly it', note: 'Chestnut cousin of the Granian.' },
    build: { archetype: 'equine', skin: 'fur', palette: { base: 0x8a4a2a, belly: 0xb87048, tip: 0x6a3418, accent: 0xc88858, eye: 0x2a1808, spark: 0xd8a070, wing: 0x9a5a36 },
      body: { len: 0.8, girth: 0.44 }, head: { shape: 'equine', size: 0.95 }, eyes: { count: 2, size: 0.13 }, ears: { type: 'point' }, wings: { type: 'feather', span: 1.4 }, legs: { count: 4, type: 'hoof' }, tail: { type: 'plume', len: 0.8 }, extras: ['mane'] },
  },
  {
    id: 'granian', name: 'Granian', latin: 'Equus alatus celer', tier: 'rare',
    blurb: 'A grey winged horse renowned above all for its tremendous speed in the air.',
    size: 1.35, speed: 2.0, roam: 11, diet: ['leafy_greens', 'berries'], favorite: 'berries',
    produces: { item: 'Granian hair', amount: 20, every: 104 }, unlockCost: 500,
    care: { feed: 'Grains', play: 'Race the wind with it', note: 'The fastest of the winged horses.' },
    build: { archetype: 'equine', skin: 'fur', palette: { base: 0x8a8e96, belly: 0xb0b4bc, tip: 0x6a6e76, accent: 0xc8ccd4, eye: 0x202028, spark: 0xd8dce4, wing: 0x9a9ea6 },
      body: { len: 0.8, girth: 0.42 }, head: { shape: 'equine', size: 0.95 }, eyes: { count: 2, size: 0.13 }, ears: { type: 'point' }, wings: { type: 'feather', span: 1.5 }, legs: { count: 4, type: 'hoof' }, tail: { type: 'plume', len: 0.85 }, extras: ['mane'] },
  },
  {
    id: 'chupacabra', name: 'Chupacabra', latin: 'Bestia sanguinis', tier: 'rare',
    blurb: 'An aggressive, reptilian-skinned beast of the Americas with a spined back and a thirst for blood.',
    size: 0.9, speed: 1.8, roam: 9, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat', nocturnal: true,
    produces: { item: 'Chupacabra spine', amount: 19, every: 98 }, unlockCost: 420,
    care: { feed: 'Plenty of meat', play: 'It warms slowly to a steady keeper', note: 'Newt kept one named Antonio.' },
    build: { archetype: 'beast', skin: 'scale', palette: { base: 0x4a4a40, belly: 0x6a6a58, accent: 0x2e2e26, horn: 0x8a8a70, eye: 0xd02020, spark: 0xa0a080 },
      body: { len: 0.65, girth: 0.38 }, head: { shape: 'snout', size: 0.85 }, eyes: { count: 2, size: 0.13, glow: true }, ears: { type: 'point' }, legs: { count: 4, type: 'paw' }, tail: { type: 'lizard', len: 0.7 }, extras: ['spikes', 'tusks'] },
  },
  {
    id: 'gytrash', name: 'Gytrash', latin: 'Canis spectralis', tier: 'rare',
    blurb: 'A spectral black dog of the English moors, large as a calf, with glowing eyes that loom out of the night fog.',
    size: 1.0, speed: 1.7, roam: 9, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat', nocturnal: true,
    produces: { item: 'Gytrash hair', amount: 18, every: 96 }, unlockCost: 380,
    care: { feed: 'Meat in the dark', play: 'A steady hand quiets the omen', note: 'An ill omen — or a lost soul\'s guide.' },
    build: { archetype: 'beast', skin: 'fur', palette: { base: 0x14141a, belly: 0x24242c, tip: 0x0a0a0e, accent: 0x3a3a42, eye: 0xf0c030, spark: 0xc0a040 },
      body: { len: 0.7, girth: 0.42 }, head: { shape: 'snout', size: 0.9 }, eyes: { count: 2, size: 0.15, glow: true }, ears: { type: 'point' }, legs: { count: 4, type: 'paw' }, tail: { type: 'tuft', len: 0.6 }, extras: ['mane', 'wisps'] },
  },
  {
    id: 'swooping_evil', name: 'Swooping Evil', latin: 'Malum volans', tier: 'rare',
    blurb: 'A blue-and-green winged predator that folds into a spiky cocoon and unfurls into a great leathery butterfly; its venom erases bad memories.',
    size: 0.9, speed: 2.1, roam: 11, diet: ['beetle', 'fresh_fish', 'raw_meat'], favorite: 'beetle',
    produces: { item: 'Swooping Evil venom', amount: 22, every: 106 }, unlockCost: 480,
    care: { feed: 'Brains... or beetles', play: 'Let it swoop and cocoon', note: 'Newt used one to great effect.' },
    build: { archetype: 'insectoid', skin: 'scale', palette: { base: 0x2a6a8a, belly: 0x3a8aaa, accent: 0x4ad0a0, horn: 0x80f0c0, eye: 0xc8e040, spark: 0x60f0c0, wing: 0x3aa0c0 },
      body: { len: 0.5, girth: 0.3 }, head: { shape: 'round', size: 0.8 }, eyes: { count: 2, size: 0.13, glow: true }, wings: { type: 'bat', span: 1.3 }, legs: { count: 2, type: 'talon' }, tail: { type: 'scorpion', len: 0.5 }, extras: ['spikes', 'crest'] },
  },

  // ── ULTRA RARE ──
  {
    id: 'griffin', name: 'Griffin', latin: 'Gryphus aquilae', tier: 'ultra',
    blurb: 'A noble beast with the head, wings and taloned forelegs of a great eagle, and the powerful hindquarters of a lion.',
    size: 1.5, speed: 1.7, roam: 10, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat',
    produces: { item: 'Griffin feather', amount: 28, every: 124 }, unlockCost: 820,
    care: { feed: 'Raw flesh', play: 'Win its fierce loyalty', note: 'Guards gold and treasure of old.' },
    build: { archetype: 'beast', skin: 'feather', palette: { base: 0x9a7a3a, belly: 0xc8a860, accent: 0xe0c878, horn: 0xe8c040, eye: 0xe0a030, spark: 0xffe09a, wing: 0xb89a52 },
      body: { len: 0.85, girth: 0.5 }, head: { shape: 'beak', size: 1.0 }, eyes: { count: 2, size: 0.14, glow: true }, wings: { type: 'feather', span: 1.6 }, legs: { count: 4, type: 'talon' }, tail: { type: 'tuft', len: 0.7 }, extras: ['mane', 'crest'] },
  },
  {
    id: 'troll', name: 'Mountain Troll', latin: 'Gigas montanus', tier: 'ultra',
    blurb: 'A twelve-foot, dull-witted brute of granite-grey skin and immense strength, smelling foully and wielding a club.',
    size: 1.8, speed: 1.0, roam: 8, habitat: 'mountain', diet: ['raw_meat', 'leafy_greens'], favorite: 'raw_meat',
    produces: { item: 'Troll booger', amount: 24, every: 120 }, unlockCost: 700,
    care: { feed: 'Whole sheep', play: 'Keep it from clubbing things', note: 'Strong, stupid, and very smelly.' },
    build: { archetype: 'humanoid', skin: 'hide', palette: { base: 0x6a7068, belly: 0x8a9082, accent: 0x4a504a, eye: 0x201810, spark: 0x9aa090 },
      body: { len: 0.7, girth: 0.56 }, head: { shape: 'round', size: 0.9 }, eyes: { count: 2, size: 0.1 }, legs: { count: 2, type: 'paw' }, extras: ['tusks'] },
  },
  {
    id: 'erkling', name: 'Erkling', latin: 'Elf maleficus', tier: 'ultra',
    blurb: 'A three-foot, elfish creature of the Black Forest with a pointed face and a high cackling laugh that lures children away.',
    size: 0.9, speed: 1.8, roam: 9, habitat: 'forest', diet: ['sweet_truffle', 'berries', 'beetle'], favorite: 'sweet_truffle', nocturnal: true,
    produces: { item: 'Erkling charm', amount: 23, every: 118 }, unlockCost: 680,
    care: { feed: 'Sweets — it craves them', play: 'Resist its cackling lure', note: 'Heavily suppressed by German wizards.' },
    build: { archetype: 'humanoid', skin: 'smooth', palette: { base: 0x9a8a6a, belly: 0xb8a888, accent: 0x6a5a3a, eye: 0xc8a030, spark: 0xd8c090 },
      body: { len: 0.45, girth: 0.24 }, head: { shape: 'round', size: 1.1 }, eyes: { count: 2, size: 0.13 }, ears: { type: 'long' }, legs: { count: 2, type: 'paw' }, extras: ['crest'] },
  },
  {
    id: 'cockatrice', name: 'Cockatrice', latin: 'Gallus serpentis', tier: 'ultra',
    blurb: 'A monstrous winged beast, half giant rooster and half dragon, whose crow and gaze can prove fatal.',
    size: 1.4, speed: 1.6, roam: 9, diet: ['raw_meat', 'beetle', 'fresh_fish'], favorite: 'raw_meat',
    produces: { item: 'Cockatrice feather', amount: 26, every: 122 }, unlockCost: 760,
    care: { feed: 'Vermin & meat', play: 'Avert your eyes from its crow', note: 'A serpent\'s tail, a cockerel\'s crest.' },
    build: { archetype: 'avian', skin: 'feather', palette: { base: 0x8a3a3a, belly: 0xb85a4a, accent: 0xe0a030, horn: 0xe0c040, eye: 0xe04020, spark: 0xff8050, wing: 0x6a2a2a },
      body: { len: 0.7, girth: 0.38 }, head: { shape: 'beak', size: 0.9 }, eyes: { count: 2, size: 0.13, glow: true }, wings: { type: 'bat', span: 1.3 }, legs: { count: 2, type: 'talon' }, tail: { type: 'lizard', len: 0.8 }, extras: ['crest'] },
  },

  // ── LEGENDARY ──
  {
    id: 'swedish_shortsnout', name: 'Swedish Short-Snout', latin: 'Draco caeruleus', tier: 'legendary',
    blurb: 'A handsome silvery-blue dragon of the wild Scandinavian mountains, whose brilliant blue flame burns wood and bone to ash.',
    size: 1.85, speed: 1.5, roam: 10, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat',
    produces: { item: 'dragon scale (silver-blue)', amount: 44, every: 154 }, unlockCost: 2000,
    care: { feed: 'Large game', play: 'Its blue flame is dazzling', note: 'Prized hide of silvery blue.' },
    build: { archetype: 'dragon', skin: 'scale', palette: { base: 0x6a8ab0, belly: 0x9ab8d8, accent: 0x4a6a90, horn: 0xc8d0e0, eye: 0xe0e040, spark: 0x60a0ff, wing: 0x5a7aa0 },
      body: { len: 0.95, girth: 0.56 }, head: { shape: 'draconic', size: 0.9 }, eyes: { count: 2, size: 0.13, glow: true }, horns: { type: 'pair', size: 0.26 }, wings: { type: 'bat', span: 1.55 }, legs: { count: 4, type: 'talon' }, tail: { type: 'lizard', len: 0.95 }, extras: ['spikes'] },
  },
  {
    id: 'romanian_longhorn', name: 'Romanian Longhorn', latin: 'Draco longicornis', tier: 'legendary',
    blurb: 'A dark-green dragon with long, glittering golden horns it uses to gore its prey before roasting it.',
    size: 1.9, speed: 1.4, roam: 10, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat',
    produces: { item: 'longhorn horn', amount: 45, every: 155 }, unlockCost: 2100,
    care: { feed: 'Whole carcasses', play: 'Beware the great golden horns', note: 'Its horns are a precious potion ingredient.' },
    build: { archetype: 'dragon', skin: 'scale', palette: { base: 0x2e5a32, belly: 0x4a7a48, accent: 0x1e3e22, horn: 0xe8c040, eye: 0xe0c030, spark: 0xff8030, wing: 0x244a28 },
      body: { len: 0.95, girth: 0.56 }, head: { shape: 'draconic', size: 0.95 }, eyes: { count: 2, size: 0.13, glow: true }, horns: { type: 'antler', size: 0.32 }, wings: { type: 'bat', span: 1.55 }, legs: { count: 4, type: 'talon' }, tail: { type: 'lizard', len: 0.95 }, extras: ['spikes'] },
  },
  {
    id: 'mountain_giant', name: 'Mountain Giant', latin: 'Gigas giganteus', tier: 'legendary',
    blurb: 'A twenty-five-foot colossus of the high mountains, slow and savage, who could crush a cottage underfoot.',
    size: 1.95, speed: 0.9, roam: 9, habitat: 'mountain', diet: ['raw_meat', 'leafy_greens', 'fresh_fish'], favorite: 'raw_meat',
    produces: { item: 'giant\'s toenail', amount: 40, every: 150 }, unlockCost: 1700,
    care: { feed: 'Mountain goats by the dozen', play: 'Patience earns a gentle giant', note: 'Fewer remain each year.' },
    build: { archetype: 'humanoid', skin: 'hide', palette: { base: 0x8a7a6a, belly: 0xa89a86, accent: 0x5a4e42, eye: 0x2a1e12, spark: 0xc0b0a0 },
      body: { len: 0.8, girth: 0.6 }, head: { shape: 'round', size: 0.85 }, eyes: { count: 2, size: 0.11 }, legs: { count: 2, type: 'paw' }, extras: ['mane', 'beard'] },
  },
  {
    id: 'giant_squid', name: 'Giant Squid', latin: 'Architeuthis amabilis', tier: 'legendary',
    blurb: 'The gentle, semi-domesticated colossus of the Black Lake, all rubbery tentacles and great calm eyes.',
    size: 1.8, speed: 1.1, roam: 9, habitat: 'coast', diet: ['fresh_fish', 'beetle'], favorite: 'fresh_fish', nocturnal: true,
    produces: { item: 'squid ink', amount: 38, every: 148 }, unlockCost: 1600,
    care: { feed: 'Shoals of fish', play: 'It enjoys a gentle tickle', note: 'Surprisingly friendly to students.' },
    build: { archetype: 'amorphous', skin: 'smooth', palette: { base: 0xc06a8a, belly: 0xe09ab0, accent: 0x9a4a6a, eye: 0x201018, spark: 0xf0b0c8 },
      body: { len: 0.6, girth: 0.46 }, head: { shape: 'round', size: 1.0 }, eyes: { count: 2, size: 0.2 }, legs: { count: 8, type: 'stick' }, extras: ['antennae'] },
  },
  {
    id: 'horned_serpent', name: 'Horned Serpent', latin: 'Serpens cornutus', tier: 'legendary',
    blurb: 'A great North American serpent bearing a single jewel in its brow that blazes to warn of danger; one gave Ilvermorny its heart.',
    size: 1.8, speed: 1.3, roam: 9, diet: ['raw_meat', 'fresh_fish'], favorite: 'raw_meat', nocturnal: true,
    produces: { item: 'Horned Serpent horn', amount: 42, every: 152 }, unlockCost: 1900,
    care: { feed: 'Whole prey', play: 'Watch the jewel in its brow flare', note: 'A shaving of its horn is a wand core.' },
    build: { archetype: 'serpent', skin: 'scale', palette: { base: 0x2a4a6a, belly: 0x4a7a9a, accent: 0x1a2e44, horn: 0x80e0ff, eye: 0xe0c030, spark: 0x80e0ff },
      body: { len: 1.3, girth: 0.4 }, head: { shape: 'draconic', size: 1.0 }, eyes: { count: 2, size: 0.15, glow: true }, horns: { type: 'single', size: 0.3 }, legs: { count: 0, type: 'none' }, tail: { type: 'serpent', len: 1.0 }, extras: ['gem', 'crest'] },
  },

  // ── MYTHIC ──
  {
    id: 'zouwu', name: 'Zouwu', latin: 'Felis quinquecolor', tier: 'mythic',
    blurb: 'An elephant-sized Chinese cat of five brilliant colours, with a vast plumed tail, able to cross a thousand miles in a day.',
    size: 1.7, speed: 2.0, roam: 12, diet: ['raw_meat', 'fresh_fish', 'gourmet_treat'], favorite: 'raw_meat',
    produces: { item: 'Zouwu whisker', amount: 50, every: 160 }, unlockCost: 3200,
    care: { feed: 'Much meat — and a feathered lure', play: 'A dangling toy delights this giant cat', note: 'Fearsome, yet it plays like a kitten.' },
    build: { archetype: 'beast', skin: 'fur', palette: { base: 0x8a3a6a, belly: 0xd86a40, accent: 0x40a0c0, horn: 0xe0c040, eye: 0xe0d030, spark: 0xffd040, pattern: 'spots' },
      body: { len: 0.95, girth: 0.56 }, head: { shape: 'feline', size: 1.0 }, eyes: { count: 2, size: 0.15, glow: true }, ears: { type: 'tuft' }, legs: { count: 4, type: 'paw' }, tail: { type: 'plume', len: 1.1 }, extras: ['mane', 'whiskers'] },
  },
  {
    id: 'qilin', name: 'Qilin', latin: 'Cervus divinus', tier: 'mythic',
    blurb: 'A pure and gentle dragon-deer of Eastern lore that can look into a soul; it bows only to the truly good of heart.',
    size: 1.3, speed: 1.5, roam: 9, diet: ['leafy_greens', 'berries', 'honey_pot', 'gourmet_treat'], favorite: 'honey_pot',
    produces: { item: 'Qilin scale', amount: 52, every: 165 }, unlockCost: 3400,
    care: { feed: 'Sweet greens & purity of heart', play: 'Walk gently; it sees who you are', note: 'Its bow once chose a wizarding leader.' },
    build: { archetype: 'equine', skin: 'scale', palette: { base: 0xc8b070, belly: 0xe8d8a0, accent: 0x88c0b0, horn: 0xfff0c0, eye: 0x3a3010, spark: 0xfff0b0 },
      body: { len: 0.72, girth: 0.4 }, head: { shape: 'draconic', size: 0.9 }, eyes: { count: 2, size: 0.15, glow: true }, ears: { type: 'point' }, horns: { type: 'antler', size: 0.24 }, legs: { count: 4, type: 'hoof' }, tail: { type: 'plume', len: 0.7 }, extras: ['mane', 'beard'] },
  },
  {
    id: 'leviathan', name: 'Leviathan', latin: 'Monstrum profundi', tier: 'mythic',
    blurb: 'A primordial sea-monster of unfathomable size, its scaled coils and finned crest breaching from the deepest ocean trenches.',
    size: 1.95, speed: 1.2, roam: 11, habitat: 'coast', diet: ['fresh_fish', 'raw_meat', 'gourmet_treat'], favorite: 'fresh_fish', nocturnal: true,
    produces: { item: 'Leviathan scale', amount: 54, every: 168 }, unlockCost: 3600,
    care: { feed: 'Whole shoals & whales', play: 'Watch its vast coils surface', note: 'Older than wizardkind itself.' },
    build: { archetype: 'serpent', skin: 'scale', palette: { base: 0x1a3a4a, belly: 0x2e5a6a, accent: 0x4a8a9a, horn: 0x88c0d0, eye: 0x60f0d0, spark: 0x70d0f0 },
      body: { len: 1.45, girth: 0.46 }, head: { shape: 'draconic', size: 1.05 }, eyes: { count: 2, size: 0.16, glow: true }, legs: { count: 0, type: 'none' }, tail: { type: 'fish', len: 1.1 }, extras: ['crest', 'spikes', 'frill'] },
  },
];
